// 攻略型・親カテゴリ（観察視点）18問
// 対象タイプ：jin_59〜jin_73（15タイプ）

export const ATTACK_PARENT_QUESTIONS = [

  {
    id: 'atk_p_001',
    type: 'entry',
    order: 1,
    text: 'あなたが自分で決めた選択を親に話したとき、最初の反応は？',
    discriminates: [],
    choices: [
      {
        id: 'override',
        label: '自分の意見を上乗せして「こうしたほうがいい」と言い換える',
        biasHints: { B3: 2, B6: 2 },
        jungShadowHints: { Te: 2, Si: 1 },
        attackTypeHints: { jin_59: 2, jin_64: 2, jin_62: 1 },
        tags: ['override'],
      },
      {
        id: 'worry',
        label: 'まずリスクや失敗した場合の話をする',
        biasHints: { B1: 3, B6: 1 },
        jungShadowHints: { Si: 2, Ni: 1 },
        attackTypeHints: { jin_61: 3, jin_59: 1 },
        tags: ['loss_focus'],
      },
      {
        id: 'question',
        label: '「なんで？」「誰と決めたの？」と経緯を確認する',
        biasHints: { B3: 2, B4: 1 },
        jungShadowHints: { Fe: 2, Te: 1 },
        attackTypeHints: { jin_69: 2, jin_65: 2, jin_60: 1 },
        tags: ['process_check'],
      },
      {
        id: 'accept',
        label: '「あなたが決めたなら」とすぐ受け入れる',
        biasHints: {},
        jungShadowHints: { Fi: 1 },
        attackTypeHints: { jin_68: 2, jin_70: 2 },
        tags: ['accepting'],
      },
    ],
  },

  {
    id: 'atk_p_002',
    type: 'entry',
    order: 2,
    text: '親が「心配している」と言うとき、その心配はどんな形で出てきますか？',
    discriminates: [],
    choices: [
      {
        id: 'control',
        label: '連絡頻度が増え、行動を確認しようとする',
        biasHints: { B1: 2, B4: 2 },
        jungShadowHints: { Te: 1, Si: 2 },
        attackTypeHints: { jin_59: 3, jin_69: 2 },
        tags: ['surveillance'],
      },
      {
        id: 'lecture',
        label: '過去の失敗例や自分の経験談を持ち出す',
        biasHints: { B7: 2, B6: 2 },
        jungShadowHints: { Si: 3 },
        attackTypeHints: { jin_62: 3, jin_71: 2 },
        tags: ['past_reference'],
      },
      {
        id: 'silent_guilt',
        label: '「いいよ、いいよ」と言いながら雰囲気が重くなる',
        biasHints: { B8: 2, B11: 2 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_63: 3, jin_73: 2 },
        tags: ['passive_pressure'],
      },
      {
        id: 'direct',
        label: '「○○は危ない」「やめなさい」とはっきり言う',
        biasHints: { B1: 2, B5: 1 },
        jungShadowHints: { Te: 2, Fi: 1 },
        attackTypeHints: { jin_66: 2, jin_59: 1 },
        tags: ['direct_block'],
      },
    ],
  },

  {
    id: 'atk_p_003',
    type: 'probe',
    text: '親が「あなたのため」と言うとき、実際の動きはどちらに近いですか？',
    discriminates: [],
    choices: [
      {
        id: 'comparison',
        label: '兄弟・友達・近所の子と比較する',
        biasHints: { B4: 3, B7: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_60: 3, jin_71: 3 },
        tags: ['comparison'],
      },
      {
        id: 'past_success',
        label: '自分が若いころにやってきた方法を勧める',
        biasHints: { B6: 3, B7: 2 },
        jungShadowHints: { Si: 3 },
        attackTypeHints: { jin_62: 3 },
        tags: ['past_method'],
      },
      {
        id: 'override_choice',
        label: '本人の希望を聞かずに手配や根回しをしてしまう',
        biasHints: { B5: 2, B3: 2 },
        jungShadowHints: { Te: 3 },
        attackTypeHints: { jin_64: 3, jin_59: 2 },
        tags: ['unilateral'],
      },
      {
        id: 'genuine',
        label: '希望を聞いて、一緒に考えようとする',
        biasHints: {},
        jungShadowHints: { Fi: 1, Fe: 1 },
        attackTypeHints: { jin_68: 3, jin_70: 2 },
        tags: ['collaborative'],
      },
    ],
  },

  {
    id: 'atk_p_004',
    type: 'probe',
    text: 'あなたが親に「ノー」を伝えたとき、その場の反応は？',
    discriminates: [],
    choices: [
      {
        id: 'silent_cold',
        label: '黙って会話が終わり、しばらく連絡が減る',
        biasHints: { B9: 2, B11: 2 },
        jungShadowHints: { Fi: 2, Fe: 1 },
        attackTypeHints: { jin_67: 2, jin_63: 1 },
        tags: ['withdrawal'],
      },
      {
        id: 'repeat',
        label: '日を変えてまた同じ提案を繰り返す',
        biasHints: { B6: 2, B3: 2 },
        jungShadowHints: { Si: 2, Te: 1 },
        attackTypeHints: { jin_59: 2, jin_61: 2 },
        tags: ['repeat_push'],
      },
      {
        id: 'guilt',
        label: '「親の気持ちもわかってほしい」と感情面で訴える',
        biasHints: { B8: 3, B11: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_63: 3, jin_73: 3 },
        tags: ['guilt_trip'],
      },
      {
        id: 'ok',
        label: '「そうか」と受け入れて引く',
        biasHints: {},
        jungShadowHints: {},
        attackTypeHints: { jin_68: 3, jin_70: 2 },
        tags: ['respect'],
      },
    ],
  },

  {
    id: 'atk_p_005',
    type: 'probe',
    text: '親が「昔はよかった」と言うとき、話の向かい先は？',
    discriminates: [],
    choices: [
      {
        id: 'self_glory',
        label: '自分の若いころの苦労や成功体験',
        biasHints: { B5: 2, B7: 2 },
        jungShadowHints: { Si: 2, Te: 1 },
        attackTypeHints: { jin_62: 3 },
        tags: ['self_glory'],
      },
      {
        id: 'world_changed',
        label: '今の世の中や若者への不満',
        biasHints: { B6: 3, B3: 2 },
        jungShadowHints: { Si: 3, Te: 1 },
        attackTypeHints: { jin_65: 2, jin_62: 1 },
        tags: ['world_complaint'],
      },
      {
        id: 'family_bond',
        label: '家族がまとまっていた時代の話',
        biasHints: { B4: 2, B8: 2 },
        jungShadowHints: { Fe: 3, Si: 1 },
        attackTypeHints: { jin_60: 2, jin_63: 1, jin_65: 2 },
        tags: ['family_bond'],
      },
    ],
  },

  {
    id: 'atk_p_006',
    type: 'probe',
    text: '親がストレスを感じているとき、その出し方は？',
    discriminates: [],
    choices: [
      {
        id: 'irritable',
        label: '些細なことに当たりが強くなる・声のトーンが変わる',
        biasHints: { B8: 2, B2: 1 },
        jungShadowHints: { Te: 2, Se: 1 },
        attackTypeHints: { jin_66: 3 },
        tags: ['irritable'],
      },
      {
        id: 'martyrdom',
        label: '「私だけが頑張っている」という言葉が増える',
        biasHints: { B9: 3, B11: 2 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_63: 2, jin_73: 3 },
        tags: ['martyrdom'],
      },
      {
        id: 'busy_escape',
        label: '用事や掃除など、動き続けることで回避する',
        biasHints: { B2: 2, B6: 1 },
        jungShadowHints: { Si: 2, Se: 1 },
        attackTypeHints: { jin_59: 2 },
        tags: ['busy_escape'],
      },
      {
        id: 'silence',
        label: '黙って距離を置く',
        biasHints: { B9: 1 },
        jungShadowHints: { Ti: 2, Fi: 1 },
        attackTypeHints: { jin_67: 3 },
        tags: ['silent_withdrawal'],
      },
    ],
  },

  {
    id: 'atk_p_007',
    type: 'probe',
    text: 'その親はあなたに電話・メッセージを送る頻度はどのくらいですか？',
    discriminates: [],
    choices: [
      {
        id: 'daily_check',
        label: 'ほぼ毎日・返信がないと追いかけてくる',
        biasHints: { B1: 2, B4: 2 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_59: 3, jin_69: 3 },
        tags: ['surveillance'],
      },
      {
        id: 'worry_trigger',
        label: '何か不安なことがあったときだけ増える',
        biasHints: { B1: 3, B6: 1 },
        jungShadowHints: { Ni: 2, Si: 1 },
        attackTypeHints: { jin_61: 2, jin_72: 1 },
        tags: ['anxiety_trigger'],
      },
      {
        id: 'occasions',
        label: '行事・誕生日・節目のとき',
        biasHints: {},
        jungShadowHints: { Fe: 1, Si: 1 },
        attackTypeHints: { jin_68: 1, jin_70: 1, jin_65: 1 },
        tags: ['occasions'],
      },
      {
        id: 'rare',
        label: 'ほとんど連絡してこない',
        biasHints: {},
        jungShadowHints: { Ti: 1, Fi: 1 },
        attackTypeHints: { jin_70: 2, jin_68: 1 },
        tags: ['low_contact'],
      },
    ],
  },

  {
    id: 'atk_p_008',
    type: 'probe',
    text: 'その親が「うれしそう」にしているのは、どんな場面が多いですか？',
    discriminates: [],
    choices: [
      {
        id: 'public_success',
        label: 'あなたが社会的に評価されたとき',
        biasHints: { B4: 2, B5: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_65: 3, jin_60: 2 },
        tags: ['status_proud'],
      },
      {
        id: 'family_together',
        label: '家族全員が揃って話をしているとき',
        biasHints: { B4: 2, B8: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_63: 2, jin_69: 2 },
        tags: ['family_together'],
      },
      {
        id: 'ask_advice',
        label: 'あなたから相談や意見を求められたとき',
        biasHints: { B5: 2, B7: 1 },
        jungShadowHints: { Si: 2, Te: 1 },
        attackTypeHints: { jin_62: 2, jin_59: 1 },
        tags: ['asked_advice'],
      },
      {
        id: 'just_being',
        label: 'あなたの顔を見るだけで、ただうれしそう',
        biasHints: {},
        jungShadowHints: { Fi: 2 },
        attackTypeHints: { jin_68: 3, jin_70: 2 },
        tags: ['unconditional'],
      },
    ],
  },

  {
    id: 'atk_p_009',
    type: 'probe',
    text: 'その親はあなたの友人・交際相手について、何か言ってきますか？',
    discriminates: [],
    choices: [
      {
        id: 'background_check',
        label: '職業・家族構成・学歴など属性を気にする',
        biasHints: { B4: 2, B3: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_65: 3, jin_60: 2 },
        tags: ['status_check'],
      },
      {
        id: 'wants_to_meet',
        label: 'とにかく会わせてほしい・連れてきてと言う',
        biasHints: { B4: 2, B11: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_69: 3 },
        tags: ['wants_to_meet'],
      },
      {
        id: 'worry_influence',
        label: '「変な人に引っ張られないか」と心配する',
        biasHints: { B1: 2, B6: 1 },
        jungShadowHints: { Si: 2, Ni: 1 },
        attackTypeHints: { jin_61: 2, jin_59: 1 },
        tags: ['worry_influence'],
      },
      {
        id: 'no_comment',
        label: 'あなたが選んだ人なら、と特に何も言わない',
        biasHints: {},
        jungShadowHints: { Fi: 1 },
        attackTypeHints: { jin_68: 2, jin_70: 2 },
        tags: ['no_comment'],
      },
    ],
  },

  {
    id: 'atk_p_010',
    type: 'probe',
    text: 'その親の感情が急に変わることがありますか？',
    discriminates: [],
    choices: [
      {
        id: 'mood_swings',
        label: 'よく変わる・機嫌の読めないことがある',
        biasHints: { B8: 3, B2: 2 },
        jungShadowHints: { Se: 2, Fe: 1 },
        attackTypeHints: { jin_66: 3, jin_72: 3 },
        tags: ['mood_swings'],
      },
      {
        id: 'slow_builds',
        label: '普段は穏やかだが、ある一線を越えると急に崩れる',
        biasHints: { B9: 2, B11: 1 },
        jungShadowHints: { Fe: 2, Fi: 1 },
        attackTypeHints: { jin_63: 2, jin_67: 2 },
        tags: ['slow_build'],
      },
      {
        id: 'stable',
        label: 'ほぼ安定している',
        biasHints: {},
        jungShadowHints: {},
        attackTypeHints: { jin_70: 2, jin_68: 2 },
        tags: ['stable'],
      },
      {
        id: 'event_triggered',
        label: '特定の話題（お金・仕事・家族）が出ると変わる',
        biasHints: { B1: 1, B8: 1 },
        jungShadowHints: { Fi: 2, Si: 1 },
        attackTypeHints: { jin_64: 2, jin_67: 1 },
        tags: ['event_triggered'],
      },
    ],
  },

  {
    id: 'atk_p_011',
    type: 'probe',
    text: 'その親はあなたを他の人に紹介するとき、どんな言い方をしますか？',
    discriminates: [],
    choices: [
      {
        id: 'achievement_focus',
        label: '学校・職場・肩書など実績を先に言う',
        biasHints: { B4: 2, B7: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_60: 3, jin_65: 2 },
        tags: ['achievement_focus'],
      },
      {
        id: 'story_embellish',
        label: '自分の子育ての話や苦労話を加えて紹介する',
        biasHints: { B5: 2, B7: 2 },
        jungShadowHints: { Si: 3 },
        attackTypeHints: { jin_62: 3 },
        tags: ['parent_story'],
      },
      {
        id: 'boundary_respect',
        label: '「本人から話してもらえれば」と口数少なく紹介する',
        biasHints: {},
        jungShadowHints: { Fi: 1 },
        attackTypeHints: { jin_68: 3, jin_70: 2 },
        tags: ['boundary_respect'],
      },
      {
        id: 'possessive',
        label: '「私の子」というニュアンスが強い言い方をする',
        biasHints: { B4: 1, B11: 1 },
        jungShadowHints: { Fe: 2 },
        attackTypeHints: { jin_69: 2, jin_63: 1 },
        tags: ['possessive'],
      },
    ],
  },

  {
    id: 'atk_p_012',
    type: 'probe',
    text: 'その親が体調を崩したり老いを感じたりしたとき、あなたへの伝え方は？',
    discriminates: [],
    choices: [
      {
        id: 'subtle_guilt',
        label: '直接言わないが「疲れた」「もう歳だから」と漏らす',
        biasHints: { B11: 3, B9: 1 },
        jungShadowHints: { Fe: 2, Fi: 1 },
        attackTypeHints: { jin_73: 3, jin_63: 2 },
        tags: ['subtle_guilt'],
      },
      {
        id: 'direct_express',
        label: 'はっきり「しんどい」「病院に行った」と報告する',
        biasHints: { B8: 1 },
        jungShadowHints: { Se: 1, Te: 1 },
        attackTypeHints: { jin_66: 2, jin_64: 1 },
        tags: ['direct'],
      },
      {
        id: 'doesnt_tell',
        label: 'あまり言わない・心配させたくないと黙っている',
        biasHints: {},
        jungShadowHints: { Fi: 2, Ti: 1 },
        attackTypeHints: { jin_67: 2, jin_70: 1 },
        tags: ['silent'],
      },
      {
        id: 'exaggerate',
        label: '大げさに言って注目・世話を引き出そうとする',
        biasHints: { B1: 2, B11: 2 },
        jungShadowHints: { Fe: 2, Ni: 1 },
        attackTypeHints: { jin_61: 2, jin_73: 2 },
        tags: ['exaggerate'],
      },
    ],
  },

  {
    id: 'atk_p_013',
    type: 'probe',
    text: 'その親があなたの自立（一人暮らし・転職・結婚など）に対してとった反応は？',
    discriminates: [],
    choices: [
      {
        id: 'resist',
        label: '止めようとしたり条件を出したりした',
        biasHints: { B1: 2, B6: 2 },
        jungShadowHints: { Si: 2, Te: 1 },
        attackTypeHints: { jin_59: 3, jin_61: 2 },
        tags: ['resist'],
      },
      {
        id: 'worried_but_go',
        label: '心配はしていたが最後は「行ってらっしゃい」と送り出した',
        biasHints: { B1: 1 },
        jungShadowHints: { Ni: 1, Fi: 1 },
        attackTypeHints: { jin_61: 1, jin_68: 2 },
        tags: ['worried_supported'],
      },
      {
        id: 'encourage',
        label: '背中を押してくれた・むしろ勧めてくれた',
        biasHints: {},
        jungShadowHints: {},
        attackTypeHints: { jin_68: 3, jin_70: 3 },
        tags: ['encourage'],
      },
      {
        id: 'financial_conditions',
        label: 'お金の話や条件面を先に持ち出した',
        biasHints: { B9: 1, B7: 1 },
        jungShadowHints: { Te: 2, Si: 1 },
        attackTypeHints: { jin_64: 3 },
        tags: ['financial'],
      },
    ],
  },

  {
    id: 'atk_p_014',
    type: 'probe',
    text: 'その親ともめた後、和解はどちらから切り出されることが多いですか？',
    discriminates: [],
    choices: [
      {
        id: 'parent_sudden_nice',
        label: '親のほうから急に何事もなかったように接してくる',
        biasHints: { B12: 2, B8: 1 },
        jungShadowHints: { Fe: 2, Se: 1 },
        attackTypeHints: { jin_72: 3, jin_66: 1 },
        tags: ['sudden_nice'],
      },
      {
        id: 'you_first',
        label: 'いつもあなたから動かないと続かない',
        biasHints: { B9: 2, B11: 1 },
        jungShadowHints: { Fi: 2, Fe: 1 },
        attackTypeHints: { jin_63: 2, jin_67: 2, jin_71: 1 },
        tags: ['you_initiate'],
      },
      {
        id: 'natural_fade',
        label: '時間が経てば自然に落ち着く',
        biasHints: { B6: 1 },
        jungShadowHints: { Si: 1, Se: 1 },
        attackTypeHints: { jin_59: 2, jin_70: 1 },
        tags: ['natural_fade'],
      },
      {
        id: 'never_explicit',
        label: '明示的な和解はない・ずっとわだかまりが残る',
        biasHints: { B9: 2, B3: 1 },
        jungShadowHints: { Fi: 3 },
        attackTypeHints: { jin_67: 3, jin_63: 2 },
        tags: ['unresolved'],
      },
    ],
  },

  {
    id: 'atk_p_015',
    type: 'probe',
    text: 'その親があなたと誰かを比べるとき、比較相手は誰が多いですか？',
    discriminates: [],
    choices: [
      {
        id: 'siblings',
        label: 'きょうだい',
        biasHints: { B4: 3, B9: 1 },
        jungShadowHints: { Si: 2, Fe: 1 },
        attackTypeHints: { jin_71: 3 },
        tags: ['sibling_compare'],
      },
      {
        id: 'peers',
        label: '同世代の他人（友人の子、近所の人など）',
        biasHints: { B4: 2, B7: 2 },
        jungShadowHints: { Fe: 2 },
        attackTypeHints: { jin_60: 3, jin_65: 2 },
        tags: ['peer_compare'],
      },
      {
        id: 'own_past',
        label: '「私が若いころは」と自分の過去と比較する',
        biasHints: { B5: 2, B7: 2 },
        jungShadowHints: { Si: 3 },
        attackTypeHints: { jin_62: 3 },
        tags: ['self_compare'],
      },
      {
        id: 'no_compare',
        label: 'あなたをほかの人と比べない',
        biasHints: {},
        jungShadowHints: { Fi: 1 },
        attackTypeHints: { jin_68: 3, jin_70: 3 },
        tags: ['no_compare'],
      },
    ],
  },

  {
    id: 'atk_p_016',
    type: 'probe',
    text: 'その親は「自分が犠牲になっている」という話をすることがありますか？',
    discriminates: [],
    choices: [
      {
        id: 'often_explicit',
        label: 'よくする・感謝が足りないと言われることがある',
        biasHints: { B11: 3, B9: 2 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_73: 3, jin_63: 2 },
        tags: ['martyr'],
      },
      {
        id: 'when_pushed',
        label: '追い詰められたときだけ言う',
        biasHints: { B8: 2, B9: 1 },
        jungShadowHints: { Fi: 2, Fe: 1 },
        attackTypeHints: { jin_67: 2, jin_72: 1 },
        tags: ['when_pushed'],
      },
      {
        id: 'indirect',
        label: '言葉にはしないが行動でにじみ出る',
        biasHints: { B11: 2 },
        jungShadowHints: { Fe: 2 },
        attackTypeHints: { jin_63: 2, jin_73: 1 },
        tags: ['indirect_martyr'],
      },
      {
        id: 'never',
        label: 'そういう話はしない',
        biasHints: {},
        jungShadowHints: {},
        attackTypeHints: { jin_68: 2, jin_70: 2, jin_64: 1 },
        tags: ['no_martyr'],
      },
    ],
  },

  {
    id: 'atk_p_017',
    type: 'probe',
    text: 'その親があなたの「仕事・キャリア」について話すとき、一番の関心は何ですか？',
    discriminates: [],
    choices: [
      {
        id: 'income_stability',
        label: '収入・安定性・将来の保障',
        biasHints: { B9: 2, B7: 1 },
        jungShadowHints: { Te: 2, Si: 1 },
        attackTypeHints: { jin_64: 3, jin_65: 2 },
        tags: ['income_focus'],
      },
      {
        id: 'social_status',
        label: '会社名・肩書・世間体',
        biasHints: { B4: 2, B3: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_65: 3, jin_60: 2 },
        tags: ['status_focus'],
      },
      {
        id: 'your_happiness',
        label: 'あなたがやりがいを持てているかどうか',
        biasHints: {},
        jungShadowHints: { Fi: 2 },
        attackTypeHints: { jin_68: 3, jin_70: 3 },
        tags: ['happiness_focus'],
      },
      {
        id: 'future_risk',
        label: 'この先うまくいくのか・リスクはないか',
        biasHints: { B1: 3, B6: 1 },
        jungShadowHints: { Ni: 2, Si: 1 },
        attackTypeHints: { jin_61: 3 },
        tags: ['risk_focus'],
      },
    ],
  },

  {
    id: 'atk_p_018',
    type: 'probe',
    text: 'その親はあなたが失敗したとき、どんな反応をしますか？',
    discriminates: [],
    choices: [
      {
        id: 'told_you',
        label: '「だから言ったでしょ」「予想してた」と言う',
        biasHints: { B5: 2, B7: 2 },
        jungShadowHints: { Si: 2, Te: 1 },
        attackTypeHints: { jin_62: 3, jin_61: 2 },
        tags: ['told_you'],
      },
      {
        id: 'emotional_upset',
        label: '自分のことのように落ち込んだり怒ったりする',
        biasHints: { B8: 3, B2: 1 },
        jungShadowHints: { Se: 2, Fe: 1 },
        attackTypeHints: { jin_66: 3, jin_72: 1 },
        tags: ['emotional'],
      },
      {
        id: 'help_plan',
        label: '「どうしたらいいか一緒に考えよう」と動いてくれる',
        biasHints: {},
        jungShadowHints: { Te: 1, Fi: 1 },
        attackTypeHints: { jin_68: 2, jin_70: 2 },
        tags: ['supportive'],
      },
      {
        id: 'cold_distance',
        label: 'しばらく冷たくなる・避けられる感じがする',
        biasHints: { B9: 2 },
        jungShadowHints: { Ti: 2, Fi: 1 },
        attackTypeHints: { jin_64: 2, jin_67: 2 },
        tags: ['cold'],
      },
    ],
  },

];
