// 攻略型・恋人カテゴリ（観察視点）18問
// 対象タイプ：jin_98〜jin_112（15タイプ）

export const ATTACK_PARTNER_QUESTIONS = [

  {
    id: 'atk_pt_001',
    type: 'entry',
    order: 1,
    text: 'その人は、あなたが機嫌が悪いとき最初にどう動きますか？',
    discriminates: ['jin_98', 'jin_100', 'jin_102', 'jin_103', 'jin_109', 'jin_112'],
    choices: [
      {
        id: 'fix',
        label: '原因を特定して解決策を出そうとする',
        biasHints: { B5: 2, B3: 1 },
        jungShadowHints: { Te: 3, Ti: 1 },
        attackTypeHints: { jin_102: 3, jin_109: 2 },
        tags: ['fix_mode'],
      },
      {
        id: 'comfort',
        label: '何も言わずそばにいる・共感しようとする',
        biasHints: {},
        jungShadowHints: { Fe: 3, Fi: 1 },
        attackTypeHints: { jin_98: 3 },
        tags: ['comfort'],
      },
      {
        id: 'retreat',
        label: '空気を読んで距離を置く・嵐が過ぎるのを待つ',
        biasHints: { B6: 2, B9: 1 },
        jungShadowHints: { Si: 2, Ti: 1 },
        attackTypeHints: { jin_100: 2, jin_112: 2 },
        tags: ['retreat'],
      },
      {
        id: 'distract',
        label: '違う話題や楽しいことを持ち出して気分を変えようとする',
        biasHints: { B2: 2, B8: 1 },
        jungShadowHints: { Se: 2, Ne: 2 },
        attackTypeHints: { jin_103: 2, jin_109: 1 },
        tags: ['distract'],
      },
      {
        // 2026-07-09追加：困っていない人の逃げ場（分岐ゲート）。
        // 選択時はApp.jsx側でAkinatorループに入らずトピック選択へ戻す。
        id: 'partner_ok',
        label: '不機嫌になっても、気づけばいつも通りに戻っている',
        tags: ['topic_ok'],
      },
    ],
  },

  {
    id: 'atk_pt_002',
    type: 'entry',
    order: 2,
    text: 'その人は不満があるとき、どう伝えてきますか？',
    discriminates: ['jin_98', 'jin_99', 'jin_102', 'jin_104', 'jin_106', 'jin_109'],
    choices: [
      {
        id: 'direct_say',
        label: 'はっきり「〇〇がいやだった」と言う',
        biasHints: {},
        jungShadowHints: { Te: 2, Se: 1 },
        attackTypeHints: { jin_109: 2, jin_102: 2 },
        tags: ['direct'],
      },
      {
        id: 'hint',
        label: '言葉より態度・雰囲気で気づいてほしそう',
        biasHints: { B11: 2, B8: 2 },
        jungShadowHints: { Fe: 2, Fi: 2 },
        attackTypeHints: { jin_98: 2, jin_106: 2, jin_104: 1 },
        tags: ['hinting'],
      },
      {
        id: 'accumulate',
        label: '溜め込んで、ある日一気に出る',
        biasHints: { B9: 3, B8: 1 },
        jungShadowHints: { Fi: 3, Ni: 1 },
        attackTypeHints: { jin_104: 3, jin_99: 2 },
        tags: ['accumulate'],
      },
      {
        id: 'analytical',
        label: '「なぜそうなるのか」を論理的に説明してくる',
        biasHints: { B5: 1 },
        jungShadowHints: { Ti: 3, Te: 1 },
        attackTypeHints: { jin_102: 3 },
        tags: ['analytical_complaint'],
      },
    ],
  },

  {
    id: 'atk_pt_003',
    type: 'probe',
    text: 'その人は「将来の話」をするとき、どんな話し方をしますか？',
    discriminates: ['jin_99', 'jin_103', 'jin_104', 'jin_108', 'jin_112'],
    choices: [
      {
        id: 'concrete_plan',
        label: '具体的な時期・条件・段取りを考えながら話す',
        biasHints: { B6: 1, B7: 1 },
        jungShadowHints: { Te: 2, Si: 2, Ni: 1 },
        attackTypeHints: { jin_108: 2, jin_107: 1 },
        tags: ['concrete_plan'],
      },
      {
        id: 'vague_dream',
        label: 'ふわっとしたイメージや夢として話す',
        biasHints: { B2: 2, B5: 1 },
        jungShadowHints: { Ne: 3, Ni: 1 },
        attackTypeHints: { jin_103: 2, jin_101: 1 },
        tags: ['vague_dream'],
      },
      {
        id: 'avoid',
        label: 'あまり将来を決めたがらない・話題を変える',
        biasHints: { B2: 3, B6: 1 },
        jungShadowHints: { Se: 2, Ne: 1, Ti: 1 },
        attackTypeHints: { jin_103: 3, jin_112: 2 },
        tags: ['future_avoid'],
      },
      {
        id: 'feeling_first',
        label: 'まず「こんな気持ちになりたい」という感覚から話す',
        biasHints: { B8: 1 },
        jungShadowHints: { Fi: 3, Ni: 1 },
        attackTypeHints: { jin_104: 2, jin_99: 2 },
        tags: ['feeling_first'],
      },
    ],
  },

  {
    id: 'atk_pt_004',
    type: 'probe',
    text: 'ケンカの後、その人は仲直りをどう切り出しますか？',
    discriminates: ['jin_98', 'jin_99', 'jin_102', 'jin_103', 'jin_104', 'jin_110'],
    choices: [
      {
        id: 'apologize',
        label: 'まず謝ってくる（内容より関係修復優先）',
        biasHints: { B4: 2, B8: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_98: 3, jin_110: 2 },
        tags: ['apologize_first'],
      },
      {
        id: 'explain',
        label: '自分の言いたかったことを改めて説明してくる',
        biasHints: { B5: 2, B3: 1 },
        jungShadowHints: { Ti: 2, Te: 1 },
        attackTypeHints: { jin_102: 3 },
        tags: ['explain'],
      },
      {
        id: 'act_normal',
        label: '時間が経ったら何事もなかったように話しかけてくる',
        biasHints: { B6: 2, B2: 1 },
        jungShadowHints: { Se: 2, Si: 1 },
        attackTypeHints: { jin_103: 2, jin_112: 1 },
        tags: ['act_normal'],
      },
      {
        id: 'wait',
        label: 'こちらから動くまで待っている',
        biasHints: { B9: 2 },
        jungShadowHints: { Fi: 2, Ni: 1 },
        attackTypeHints: { jin_104: 2, jin_99: 2, jin_105: 1 },
        tags: ['wait'],
      },
    ],
  },

  {
    id: 'atk_pt_005',
    type: 'probe',
    text: 'その人があなたへの愛情を示すとき、一番多いパターンは？',
    discriminates: ['jin_98', 'jin_109'],
    choices: [
      {
        id: 'action',
        label: '何かをしてくれる（料理・手伝い・調べてくれるなど）',
        biasHints: {},
        jungShadowHints: { Te: 2, Se: 2 },
        attackTypeHints: { jin_109: 2, jin_100: 1 },
        tags: ['acts_of_service'],
      },
      {
        id: 'words',
        label: '言葉にして「好き」「ありがとう」を伝えてくれる',
        biasHints: { B8: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_98: 3 },
        tags: ['words_of_affirmation'],
      },
      {
        id: 'time',
        label: '一緒にいる時間を大事にする・予定を合わせてくれる',
        biasHints: { B4: 1 },
        jungShadowHints: { Fe: 1, Se: 1, Fi: 1 },
        attackTypeHints: { jin_98: 1, jin_99: 1, jin_103: 1 },
        tags: ['quality_time'],
      },
      {
        id: 'gifts',
        label: 'プレゼントや「これ好きかなと思って」という細かい気配り',
        biasHints: { B8: 1, B2: 1 },
        jungShadowHints: { Fe: 1, Ni: 2 },
        attackTypeHints: { jin_107: 1, jin_108: 1 },
        tags: ['gifts'],
      },
    ],
  },

  {
    id: 'atk_pt_006',
    type: 'probe',
    text: 'その人が「もう無理」と感じたとき、どんな行動をしますか？',
    discriminates: ['jin_99', 'jin_101', 'jin_102', 'jin_104', 'jin_106', 'jin_109'],
    choices: [
      {
        id: 'express',
        label: 'はっきり「つらい」「限界」と伝えてくる',
        biasHints: { B8: 1 },
        jungShadowHints: { Se: 1, Te: 2 },
        attackTypeHints: { jin_109: 2, jin_98: 1 },
        tags: ['express_limit'],
      },
      {
        id: 'disappear',
        label: '急に連絡が減る・既読スルーが増える',
        biasHints: { B9: 2, B6: 1 },
        jungShadowHints: { Fi: 3, Ni: 1 },
        attackTypeHints: { jin_104: 3, jin_99: 2, jin_101: 2 },
        tags: ['disappear'],
      },
      {
        id: 'passive_signal',
        label: '態度が変わるが理由を聞いても「別に」と言う',
        biasHints: { B11: 3, B9: 1 },
        jungShadowHints: { Fe: 2, Fi: 1 },
        attackTypeHints: { jin_106: 2, jin_101: 1 },
        tags: ['passive_signal'],
      },
      {
        id: 'talk_request',
        label: '「ちゃんと話したい」と場を設ける',
        biasHints: {},
        jungShadowHints: { Fe: 1, Ti: 2 },
        attackTypeHints: { jin_102: 2, jin_112: 1 },
        tags: ['talk_request'],
      },
    ],
  },

  {
    id: 'atk_pt_007',
    type: 'probe',
    text: 'その人はあなたが友人と出かけることについて、どんな反応をしますか？',
    discriminates: ['jin_98', 'jin_99', 'jin_100', 'jin_101', 'jin_111', 'jin_112'],
    choices: [
      {
        id: 'checks_details',
        label: '誰と・どこに・何時に帰るかを確認してくる',
        biasHints: { B9: 2, B3: 1 },
        jungShadowHints: { Fi: 2, Si: 1 },
        attackTypeHints: { jin_99: 3, jin_111: 2 },
        tags: ['checking'],
      },
      {
        id: 'ok_but_moody',
        label: '表面上は「いいよ」と言うが後でぎこちない',
        biasHints: { B12: 2, B9: 1 },
        jungShadowHints: { Fi: 2, Fe: 1 },
        attackTypeHints: { jin_101: 2, jin_110: 1 },
        tags: ['ok_but_moody'],
      },
      {
        id: 'genuinely_fine',
        label: '特に何も言わない・本当に気にしていない',
        biasHints: {},
        jungShadowHints: { Ti: 1, Se: 1 },
        attackTypeHints: { jin_112: 2, jin_100: 2 },
        tags: ['genuinely_fine'],
      },
      {
        id: 'asks_after',
        label: '「どうだった？」と後で聞いてくる',
        biasHints: { B4: 1, B8: 1 },
        jungShadowHints: { Fe: 2 },
        attackTypeHints: { jin_98: 2 },
        tags: ['asks_after'],
      },
    ],
  },

  {
    id: 'atk_pt_008',
    type: 'probe',
    text: 'その人が「ふさぎこんでいる」とき、理由を言いますか？',
    discriminates: ['jin_98', 'jin_100', 'jin_101', 'jin_104', 'jin_112'],
    choices: [
      {
        id: 'says_after_time',
        label: '少し時間が経ってから話してくれる',
        biasHints: { B9: 1 },
        jungShadowHints: { Fi: 2, Ni: 1 },
        attackTypeHints: { jin_104: 2, jin_100: 1 },
        tags: ['delayed_sharing'],
      },
      {
        id: 'hints_not_say',
        label: '態度で伝えようとするが言葉にしない',
        biasHints: { B11: 2, B9: 1 },
        jungShadowHints: { Fi: 3 },
        attackTypeHints: { jin_104: 3, jin_101: 2 },
        tags: ['hints'],
      },
      {
        id: 'doesnt_tell',
        label: '「なんでもない」と言って閉じる',
        biasHints: { B9: 2, B6: 1 },
        jungShadowHints: { Ti: 2, Si: 1 },
        attackTypeHints: { jin_100: 3, jin_112: 2 },
        tags: ['closed_off'],
      },
      {
        id: 'tells_quickly',
        label: 'すぐ「実は〜」と話してくれる',
        biasHints: { B8: 1 },
        jungShadowHints: { Fe: 2, Se: 1 },
        attackTypeHints: { jin_98: 2, jin_102: 1 },
        tags: ['open'],
      },
    ],
  },

  {
    id: 'atk_pt_009',
    type: 'probe',
    text: 'その人はあなたへの「期待」をどう表現しますか？',
    discriminates: ['jin_103', 'jin_106', 'jin_107', 'jin_108', 'jin_112'],
    choices: [
      {
        id: 'explicit',
        label: '「〇〇してほしい」「〇〇してくれたらうれしい」と明示する',
        biasHints: { B11: 2, B9: 1 },
        jungShadowHints: { Fe: 2 },
        attackTypeHints: { jin_106: 3, jin_98: 1 },
        tags: ['explicit'],
      },
      {
        id: 'by_comparison',
        label: '他の人と比べる形で伝えてくる',
        biasHints: { B7: 2, B3: 1 },
        jungShadowHints: { Si: 2, Fe: 1 },
        attackTypeHints: { jin_107: 3 },
        tags: ['comparison'],
      },
      {
        id: 'no_expectations',
        label: '期待を口にしない・あなたに委ねる',
        biasHints: {},
        jungShadowHints: { Se: 1, Ti: 1 },
        attackTypeHints: { jin_103: 2, jin_112: 2 },
        tags: ['no_expectations'],
      },
      {
        id: 'future_oriented',
        label: '「二人でこうなりたい」と将来の形で伝える',
        biasHints: { B1: 1 },
        jungShadowHints: { Ni: 2, Fe: 1 },
        attackTypeHints: { jin_108: 2, jin_109: 1 },
        tags: ['future_oriented'],
      },
    ],
  },

  {
    id: 'atk_pt_010',
    type: 'probe',
    text: 'その人は「ケンカになりそうな話題」をどう扱いますか？',
    discriminates: ['jin_98', 'jin_100', 'jin_102', 'jin_103', 'jin_104', 'jin_109'],
    choices: [
      {
        id: 'addresses',
        label: '避けずにきちんと向き合おうとする',
        biasHints: {},
        jungShadowHints: { Te: 2, Ti: 1 },
        attackTypeHints: { jin_109: 3, jin_102: 2 },
        tags: ['direct'],
      },
      {
        id: 'avoids',
        label: '話題を変える・「また今度」と先送りにする',
        biasHints: { B6: 2, B2: 1 },
        jungShadowHints: { Si: 2, Se: 1 },
        attackTypeHints: { jin_100: 3, jin_103: 2 },
        tags: ['avoids'],
      },
      {
        id: 'emotionally_redirect',
        label: '感情的になって話がずれていく',
        biasHints: { B8: 2, B9: 1 },
        jungShadowHints: { Fe: 2, Fi: 1 },
        attackTypeHints: { jin_98: 2, jin_110: 1 },
        tags: ['emotional_redirect'],
      },
      {
        id: 'brings_up_later',
        label: '後になってから蒸し返す',
        biasHints: { B9: 2, B3: 1 },
        jungShadowHints: { Fi: 2, Ni: 1 },
        attackTypeHints: { jin_104: 2, jin_108: 1 },
        tags: ['later_raise'],
      },
    ],
  },

  {
    id: 'atk_pt_011',
    type: 'probe',
    text: 'その人はSNSでのあなたの行動・投稿について何か言いますか？',
    discriminates: ['jin_99', 'jin_100', 'jin_111', 'jin_112'],
    choices: [
      {
        id: 'monitors',
        label: '見ていて反応してくる・気になる投稿を指摘する',
        biasHints: { B3: 2, B9: 1 },
        jungShadowHints: { Fi: 2, Si: 1 },
        attackTypeHints: { jin_111: 3, jin_99: 2 },
        tags: ['monitoring'],
      },
      {
        id: 'occasionally',
        label: 'たまにコメント・「見たよ」と言ってくる程度',
        biasHints: { B4: 1, B8: 1 },
        jungShadowHints: { Fe: 1, Si: 1 },
        attackTypeHints: { jin_107: 1, jin_98: 1 },
        tags: ['occasional'],
      },
      {
        id: 'not_interested',
        label: 'SNSに興味がない・あなたのも見ていない',
        biasHints: {},
        jungShadowHints: { Ti: 2 },
        attackTypeHints: { jin_112: 3, jin_100: 2 },
        tags: ['not_interested'],
      },
      {
        id: 'emotionally_reacts',
        label: '特定の投稿に強く反応する（不機嫌になるなど）',
        biasHints: { B9: 2, B12: 1 },
        jungShadowHints: { Fi: 2, Fe: 1 },
        attackTypeHints: { jin_99: 2, jin_111: 2 },
        tags: ['emotional_reaction'],
      },
    ],
  },

  {
    id: 'atk_pt_012',
    type: 'probe',
    text: 'その人が「疲れた・しんどい」と言うのは、どんなとき多いですか？',
    discriminates: ['jin_100', 'jin_101', 'jin_104', 'jin_108', 'jin_112'],
    choices: [
      {
        id: 'after_social',
        label: '人と関わった後・大勢の場に出た後',
        biasHints: { B6: 1, B2: 1 },
        jungShadowHints: { Ti: 2, Fi: 1 },
        attackTypeHints: { jin_112: 3 },
        tags: ['after_social'],
      },
      {
        id: 'things_not_go',
        label: '物事が思い通りにいかないとき',
        biasHints: { B9: 2, B1: 1 },
        jungShadowHints: { Ni: 2, Fi: 1 },
        attackTypeHints: { jin_104: 2, jin_108: 2 },
        tags: ['frustration'],
      },
      {
        id: 'unpredictable',
        label: '特にパターンがない・急に言い出す',
        biasHints: { B12: 2 },
        jungShadowHints: { Fi: 2, Se: 1 },
        attackTypeHints: { jin_101: 3 },
        tags: ['unpredictable'],
      },
      {
        id: 'rarely_says',
        label: 'あまり言わない・弱音を見せない',
        biasHints: {},
        jungShadowHints: { Ti: 2, Te: 1 },
        attackTypeHints: { jin_100: 3, jin_102: 1 },
        tags: ['rarely'],
      },
    ],
  },

  {
    id: 'atk_pt_013',
    type: 'probe',
    text: 'その人はあなたとの「思い出・記念日」を大切にしますか？',
    discriminates: ['jin_98', 'jin_103', 'jin_105', 'jin_109'],
    choices: [
      {
        id: 'very_much',
        label: '記念日を覚えていてお祝いしてくれる',
        biasHints: { B9: 1, B3: 1 },
        jungShadowHints: { Si: 2, Fe: 1 },
        attackTypeHints: { jin_105: 3, jin_98: 2 },
        tags: ['anniversary'],
      },
      {
        id: 'casually',
        label: 'あまり気にしない・記念日より今が大事',
        biasHints: { B2: 2, B6: 1 },
        jungShadowHints: { Se: 2, Ti: 1 },
        attackTypeHints: { jin_103: 3 },
        tags: ['present_focused'],
      },
      {
        id: 'creates_memories',
        label: '一緒にいい思い出を作ろうとする・写真を撮りたがる',
        biasHints: { B8: 1, B2: 1 },
        jungShadowHints: { Se: 2, Fe: 1 },
        attackTypeHints: { jin_98: 1, jin_106: 1 },
        tags: ['memory_creator'],
      },
      {
        id: 'forgets',
        label: '忘れがち・特に重要視していない',
        biasHints: { B2: 2 },
        jungShadowHints: { Te: 1, Ti: 1 },
        attackTypeHints: { jin_109: 3 },
        tags: ['forgetful'],
      },
    ],
  },

  {
    id: 'atk_pt_014',
    type: 'probe',
    text: 'その人は別れ話になったとき、どう動きますか？',
    discriminates: ['jin_98', 'jin_99', 'jin_101', 'jin_102', 'jin_104', 'jin_110'],
    choices: [
      {
        id: 'clings',
        label: '引き止める・泣く・急に優しくなる',
        biasHints: { B1: 2, B9: 1 },
        jungShadowHints: { Fe: 2, Fi: 1 },
        attackTypeHints: { jin_110: 3, jin_98: 2 },
        tags: ['cling'],
      },
      {
        id: 'goes_cold',
        label: '急に冷たくなる・話をしなくなる',
        biasHints: { B9: 2 },
        jungShadowHints: { Fi: 2, Ti: 1 },
        attackTypeHints: { jin_104: 2, jin_99: 2 },
        tags: ['cold'],
      },
      {
        id: 'argues_logic',
        label: '「なぜそうなるのか」と論理的に話し合おうとする',
        biasHints: { B5: 1, B3: 1 },
        jungShadowHints: { Ti: 2, Te: 1 },
        attackTypeHints: { jin_102: 2 },
        tags: ['logical'],
      },
      {
        id: 'disappears_returns',
        label: '一度受け入れてもしばらくしてまた戻ってくる',
        biasHints: { B12: 2, B1: 1 },
        jungShadowHints: { Fe: 1, Fi: 2 },
        attackTypeHints: { jin_110: 3, jin_101: 2 },
        tags: ['oscillate'],
      },
    ],
  },

  {
    id: 'atk_pt_015',
    type: 'probe',
    text: 'その人は「一人の時間」をどのくらい必要としていますか？',
    discriminates: ['jin_98', 'jin_99', 'jin_100', 'jin_101', 'jin_112'],
    choices: [
      {
        id: 'lots',
        label: 'かなり必要・一人の時間を守ろうとする',
        biasHints: { B6: 2, B2: 1 },
        jungShadowHints: { Ti: 2, Fi: 1 },
        attackTypeHints: { jin_112: 3, jin_100: 2 },
        tags: ['lots_alone'],
      },
      {
        id: 'little',
        label: 'あまり必要としない・一緒にいたがる',
        biasHints: { B4: 1, B8: 1 },
        jungShadowHints: { Fe: 2, Se: 1 },
        attackTypeHints: { jin_98: 2, jin_99: 2 },
        tags: ['togetherness'],
      },
      {
        id: 'moderate',
        label: '適度にある・お互いの時間も大切にする',
        biasHints: {},
        jungShadowHints: {},
        attackTypeHints: { jin_103: 1 },
        tags: ['balance'],
      },
      {
        id: 'varies',
        label: '波がある・一人になりたい時期と一緒にいたい時期がある',
        biasHints: { B12: 2 },
        jungShadowHints: { Fi: 2, Ni: 1 },
        attackTypeHints: { jin_101: 3 },
        tags: ['varies'],
      },
    ],
  },

  {
    id: 'atk_pt_016',
    type: 'probe',
    text: 'その人があなたのことを「心配している」と感じるのはどんな形ですか？',
    discriminates: ['jin_98', 'jin_99', 'jin_100', 'jin_102', 'jin_108', 'jin_112'],
    choices: [
      {
        id: 'over_checking',
        label: '頻繁に連絡してくる・どこにいるか確認する',
        biasHints: { B1: 2, B3: 1 },
        jungShadowHints: { Ni: 2, Fi: 1 },
        attackTypeHints: { jin_108: 3, jin_99: 2 },
        tags: ['over_checking'],
      },
      {
        id: 'worry_expressed',
        label: '「大丈夫？」「気をつけてね」と言葉で表現する',
        biasHints: { B1: 1, B8: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_98: 3 },
        tags: ['verbal_worry'],
      },
      {
        id: 'practical_help',
        label: '何かを調べてくれる・具体的に動いてくれる',
        biasHints: {},
        jungShadowHints: { Te: 2, Si: 1 },
        attackTypeHints: { jin_102: 2, jin_109: 1 },
        tags: ['practical'],
      },
      {
        id: 'says_nothing',
        label: '口には出さないが何となく気にかけているのがわかる',
        biasHints: {},
        jungShadowHints: { Ti: 1, Fi: 1 },
        attackTypeHints: { jin_100: 3, jin_112: 2 },
        tags: ['silent_care'],
      },
    ],
  },

  {
    id: 'atk_pt_017',
    type: 'probe',
    text: 'その人はあなたの「過去の恋愛」についてどんな態度をとりますか？',
    discriminates: ['jin_99', 'jin_100', 'jin_105', 'jin_107', 'jin_111', 'jin_112'],
    choices: [
      {
        id: 'jealous_asks',
        label: '詳しく聞きたがる・嫉妬することがある',
        biasHints: { B9: 2, B3: 1 },
        jungShadowHints: { Fi: 3 },
        attackTypeHints: { jin_99: 3, jin_111: 2 },
        tags: ['jealous'],
      },
      {
        id: 'doesnt_ask',
        label: '聞かない・あなたの過去には興味がない',
        biasHints: {},
        jungShadowHints: { Ti: 2, Se: 1 },
        attackTypeHints: { jin_112: 3, jin_100: 2 },
        tags: ['doesnt_ask'],
      },
      {
        id: 'brings_up_compare',
        label: '過去の人と比較する言い方をすることがある',
        biasHints: { B7: 2, B3: 2 },
        jungShadowHints: { Si: 2, Fe: 1 },
        attackTypeHints: { jin_105: 3, jin_107: 2 },
        tags: ['compares'],
      },
      {
        id: 'one_time_clarify',
        label: '一度だけ確認した・それ以上は掘り返さない',
        biasHints: {},
        jungShadowHints: { Ti: 1, Fe: 1 },
        attackTypeHints: { jin_102: 1, jin_108: 1 },
        tags: ['once_clarify'],
      },
    ],
  },

  {
    id: 'atk_pt_018',
    type: 'probe',
    text: 'その人は「2人のルール・約束」をどのくらい守ろうとしますか？',
    discriminates: ['jin_99', 'jin_102', 'jin_103', 'jin_105', 'jin_109'],
    choices: [
      {
        id: 'strictly',
        label: 'ルールを大切にする・過去の約束を覚えている',
        biasHints: { B9: 1, B3: 1 },
        jungShadowHints: { Si: 2, Fi: 1 },
        attackTypeHints: { jin_105: 2, jin_99: 2 },
        tags: ['strict'],
      },
      {
        id: 'mostly',
        label: 'だいたい守る・たまに忘れることはある',
        biasHints: {},
        jungShadowHints: { Fe: 1, Ti: 1 },
        attackTypeHints: { jin_102: 2, jin_108: 1 },
        tags: ['mostly'],
      },
      {
        id: 'flexible',
        label: '状況に応じて変えていい派・ルール自体を嫌がる',
        biasHints: { B2: 2, B6: 1 },
        jungShadowHints: { Se: 2, Ne: 1 },
        attackTypeHints: { jin_103: 3, jin_101: 1 },
        tags: ['flexible'],
      },
      {
        id: 'forgets',
        label: '「そんな約束あったっけ」と忘れていることが多い',
        biasHints: { B2: 2 },
        jungShadowHints: { Se: 1, Ne: 1 },
        attackTypeHints: { jin_109: 3 },
        tags: ['forgets'],
      },
    ],
  },

];
