// 攻略型・きょうだいカテゴリ（観察視点）12問
// 対象タイプ：jin_84〜jin_91（8タイプ）

export const ATTACK_SIBLING_QUESTIONS = [

  {
    id: 'atk_sb_001',
    type: 'entry',
    order: 1,
    text: 'きょうだい間で意見が食い違ったとき、その人はどうしますか？',
    discriminates: [],
    choices: [
      {
        id: 'argue',
        label: '自分の正しさを証明しようと話し続ける',
        biasHints: { B5: 2, B3: 2 },
        jungShadowHints: { Te: 2, Ti: 1 },
        attackTypeHints: { jin_84: 3 },
        tags: ['argue'],
      },
      {
        id: 'withdraw_sulk',
        label: '黙って引いて、あとで機嫌が悪い',
        biasHints: { B9: 2, B11: 1 },
        jungShadowHints: { Fi: 2, Fe: 1 },
        attackTypeHints: { jin_86: 3, jin_91: 2 },
        tags: ['sulk_withdraw'],
      },
      {
        id: 'parent_appeal',
        label: '親や第三者を巻き込む',
        biasHints: { B4: 2, B8: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_87: 2, jin_89: 2 },
        tags: ['third_party'],
      },
      {
        id: 'compromise',
        label: 'すぐ「まあいいか」と流せる',
        biasHints: { B6: 1, B2: 1 },
        jungShadowHints: { Se: 1, Ne: 1 },
        attackTypeHints: { jin_88: 2, jin_89: 1 },
        tags: ['easy_going'],
      },
    ],
  },

  {
    id: 'atk_sb_002',
    type: 'entry',
    order: 2,
    text: 'そのきょうだいは、あなたの成功や良いニュースにどう反応しますか？',
    discriminates: [],
    choices: [
      {
        id: 'compare',
        label: '自分の話に切り替える・「私も実は〜」と並列にする',
        biasHints: { B5: 2, B9: 2 },
        jungShadowHints: { Te: 1, Fe: 2 },
        attackTypeHints: { jin_84: 3, jin_87: 2 },
        tags: ['compare_self'],
      },
      {
        id: 'genuine_happy',
        label: '素直に喜んでくれる',
        biasHints: {},
        jungShadowHints: { Fe: 1, Fi: 1 },
        attackTypeHints: { jin_89: 3 },
        tags: ['genuine_joy'],
      },
      {
        id: 'practical',
        label: '「それで何か変わるの？」と実利を聞く',
        biasHints: { B1: 1, B7: 1 },
        jungShadowHints: { Te: 2, Si: 1 },
        attackTypeHints: { jin_84: 2, jin_88: 1 },
        tags: ['practical_check'],
      },
      {
        id: 'backhanded',
        label: '「すごいね」と言いながら少しだけ棘がある',
        biasHints: { B9: 3, B11: 1 },
        jungShadowHints: { Fi: 2, Fe: 2 },
        attackTypeHints: { jin_91: 3, jin_86: 2 },
        tags: ['backhanded'],
      },
    ],
  },

  {
    id: 'atk_sb_003',
    type: 'probe',
    text: '家族の集まりで、そのきょうだいが取る役割は？',
    discriminates: [],
    choices: [
      {
        id: 'organizer',
        label: '仕切りたがる・段取りを決める',
        biasHints: { B5: 2, B6: 1 },
        jungShadowHints: { Te: 3, Si: 1 },
        attackTypeHints: { jin_84: 3 },
        tags: ['organizer'],
      },
      {
        id: 'peacemaker',
        label: '空気を読んで場をつなぐ',
        biasHints: { B4: 2, B8: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_89: 3, jin_87: 2 },
        tags: ['peacemaker'],
      },
      {
        id: 'background',
        label: '端のほうで静かにしている',
        biasHints: { B6: 1 },
        jungShadowHints: { Ti: 2, Fi: 1, Si: 1 },
        attackTypeHints: { jin_88: 3, jin_86: 2 },
        tags: ['background'],
      },
      {
        id: 'entertainer',
        label: '場を盛り上げる・話題を作る',
        biasHints: { B2: 1, B5: 1 },
        jungShadowHints: { Se: 2, Ne: 2, Fe: 1 },
        attackTypeHints: { jin_90: 2 },
        tags: ['entertainer'],
      },
    ],
  },

  {
    id: 'atk_sb_004',
    type: 'probe',
    text: 'そのきょうだいが「貸して」「助けて」と言ってくるとき、どんな状況が多いですか？',
    discriminates: [],
    choices: [
      {
        id: 'emergency',
        label: '急場しのぎ・今すぐ困ったときだけ',
        biasHints: { B2: 3, B1: 1 },
        jungShadowHints: { Se: 2, Ne: 1 },
        attackTypeHints: { jin_90: 3 },
        tags: ['emergency_only'],
      },
      {
        id: 'routine',
        label: 'いつも同じパターンで頼んでくる',
        biasHints: { B6: 2, B9: 1 },
        jungShadowHints: { Si: 2, Fe: 1 },
        attackTypeHints: { jin_85: 3 },
        tags: ['routine_help'],
      },
      {
        id: 'emotional',
        label: '感情的に落ち込んでいるとき',
        biasHints: { B8: 2, B11: 1 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_86: 2, jin_91: 2 },
        tags: ['emotional_support'],
      },
      {
        id: 'plan',
        label: '大きな決断や計画のとき',
        biasHints: { B1: 2, B7: 1 },
        jungShadowHints: { Ni: 2, Te: 1 },
        attackTypeHints: { jin_84: 2, jin_89: 1 },
        tags: ['big_decision'],
      },
    ],
  },

  {
    id: 'atk_sb_005',
    type: 'probe',
    text: 'そのきょうだいは「家族のルール・慣習」に対してどんな態度をとりますか？',
    discriminates: [],
    choices: [
      {
        id: 'follows',
        label: '黙って従う・波風を立てたくない',
        biasHints: { B6: 2, B4: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_87: 2, jin_89: 1 },
        tags: ['compliant'],
      },
      {
        id: 'challenges',
        label: '「そのやり方はもう古い」と変えようとする',
        biasHints: { B5: 2, B12: 1 },
        jungShadowHints: { Te: 2, Ne: 1 },
        attackTypeHints: { jin_84: 2, jin_86: 1 },
        tags: ['challenger'],
      },
      {
        id: 'ignores',
        label: '表面上は従うが実際は無視している',
        biasHints: { B9: 2 },
        jungShadowHints: { Ti: 2, Fi: 1 },
        attackTypeHints: { jin_88: 3 },
        tags: ['ignores'],
      },
      {
        id: 'mediates',
        label: '家族間の意見をまとめようとする',
        biasHints: { B4: 2 },
        jungShadowHints: { Fe: 3 },
        attackTypeHints: { jin_89: 3 },
        tags: ['mediates'],
      },
    ],
  },

  {
    id: 'atk_sb_006',
    type: 'probe',
    text: 'そのきょうだいはあなたに「お金・物の貸し借り」を持ち出すことがありますか？',
    discriminates: [],
    choices: [
      {
        id: 'yes_often',
        label: 'よく頼んでくる・断りにくい雰囲気がある',
        biasHints: { B6: 2, B9: 2 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_85: 3, jin_90: 2 },
        tags: ['frequent_borrow'],
      },
      {
        id: 'only_urgent',
        label: '本当に困ったときだけ・返そうとする意識はある',
        biasHints: { B2: 2, B1: 1 },
        jungShadowHints: { Se: 2 },
        attackTypeHints: { jin_90: 3 },
        tags: ['emergency_only'],
      },
      {
        id: 'rarely',
        label: 'ほとんどない',
        biasHints: {},
        jungShadowHints: { Ti: 1, Te: 1 },
        attackTypeHints: { jin_84: 1, jin_88: 2 },
        tags: ['rarely'],
      },
      {
        id: 'never',
        label: 'まったくない・自立している',
        biasHints: {},
        jungShadowHints: { Fi: 1, Ti: 1 },
        attackTypeHints: { jin_88: 2, jin_86: 1 },
        tags: ['never'],
      },
    ],
  },

  {
    id: 'atk_sb_007',
    type: 'probe',
    text: 'そのきょうだいはあなたとの「過去の出来事」を会話に引き出しますか？',
    discriminates: [],
    choices: [
      {
        id: 'old_wounds',
        label: '昔の揉め事・傷ついた記憶を今でも持ち出す',
        biasHints: { B9: 3, B3: 1 },
        jungShadowHints: { Fi: 3, Si: 1 },
        attackTypeHints: { jin_86: 3, jin_91: 3 },
        tags: ['old_wounds'],
      },
      {
        id: 'positive_memories',
        label: '楽しかった思い出を出して仲良くしようとする',
        biasHints: { B8: 1, B4: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_89: 2, jin_87: 1 },
        tags: ['positive_memories'],
      },
      {
        id: 'context_only',
        label: '説明のために出すことはあるが根に持つ感じはない',
        biasHints: {},
        jungShadowHints: { Si: 1, Ti: 1 },
        attackTypeHints: { jin_89: 1, jin_84: 1 },
        tags: ['context_only'],
      },
      {
        id: 'rarely_past',
        label: 'あまり過去の話はしない',
        biasHints: {},
        jungShadowHints: { Se: 1, Ne: 1 },
        attackTypeHints: { jin_88: 2, jin_84: 1 },
        tags: ['rarely_past'],
      },
    ],
  },

  {
    id: 'atk_sb_008',
    type: 'probe',
    text: 'そのきょうだいは親からの扱われ方に「えこひいき」を感じていそうですか？',
    discriminates: [],
    choices: [
      {
        id: 'strong_resentment',
        label: '明らかに根に持っている・話題に出すことがある',
        biasHints: { B9: 3, B3: 2 },
        jungShadowHints: { Fi: 3 },
        attackTypeHints: { jin_91: 3, jin_86: 2 },
        tags: ['resentment'],
      },
      {
        id: 'mentions_sometimes',
        label: '時折口にするが引きずっている感じはない',
        biasHints: { B9: 2, B11: 1 },
        jungShadowHints: { Fe: 1, Fi: 1 },
        attackTypeHints: { jin_91: 2, jin_87: 2 },
        tags: ['mentions'],
      },
      {
        id: 'seems_fine',
        label: '特に気にしていないように見える',
        biasHints: {},
        jungShadowHints: {},
        attackTypeHints: { jin_88: 2, jin_89: 1 },
        tags: ['fine'],
      },
      {
        id: 'doesnt_show',
        label: '言わないだけで内心どうかわからない',
        biasHints: { B9: 1 },
        jungShadowHints: { Ti: 1, Fi: 1 },
        attackTypeHints: { jin_84: 1, jin_88: 1 },
        tags: ['unknown'],
      },
    ],
  },

  {
    id: 'atk_sb_009',
    type: 'probe',
    text: 'そのきょうだいとの連絡頻度はどのくらいですか？',
    discriminates: [],
    choices: [
      {
        id: 'frequent',
        label: '頻繁にある・なんでも報告してくる',
        biasHints: { B4: 2, B11: 1 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_85: 3, jin_87: 2 },
        tags: ['frequent'],
      },
      {
        id: 'when_needed',
        label: '必要なときだけ・要件があるときのみ',
        biasHints: { B2: 1 },
        jungShadowHints: { Se: 1, Te: 1 },
        attackTypeHints: { jin_90: 2, jin_84: 1 },
        tags: ['when_needed'],
      },
      {
        id: 'infrequent',
        label: 'めったにない・しばらく連絡が途絶えることも',
        biasHints: { B9: 1, B6: 1 },
        jungShadowHints: { Ti: 2, Fi: 1 },
        attackTypeHints: { jin_88: 3, jin_86: 1 },
        tags: ['infrequent'],
      },
      {
        id: 'you_initiate',
        label: 'あなたから連絡しないと来ない',
        biasHints: { B9: 2 },
        jungShadowHints: { Fi: 2, Ti: 1 },
        attackTypeHints: { jin_88: 2, jin_86: 1, jin_91: 1 },
        tags: ['you_initiate'],
      },
    ],
  },

  {
    id: 'atk_sb_010',
    type: 'probe',
    text: 'そのきょうだいが「大変だ・困っている」と言ってくるとき、その性質は？',
    discriminates: [],
    choices: [
      {
        id: 'chronic',
        label: 'いつも何かしら困っている・慢性的',
        biasHints: { B6: 2, B9: 2 },
        jungShadowHints: { Fe: 2, Si: 1 },
        attackTypeHints: { jin_85: 3 },
        tags: ['chronic'],
      },
      {
        id: 'sudden_emergency',
        label: '突然やってくる・事前の相談なし',
        biasHints: { B2: 3, B1: 1 },
        jungShadowHints: { Se: 2 },
        attackTypeHints: { jin_90: 3 },
        tags: ['sudden'],
      },
      {
        id: 'emotional_complaint',
        label: '感情的な悩みが多い・誰かへの不満が中心',
        biasHints: { B8: 2, B9: 2 },
        jungShadowHints: { Fi: 2, Fe: 1 },
        attackTypeHints: { jin_86: 2, jin_91: 2 },
        tags: ['emotional'],
      },
      {
        id: 'practical_issue',
        label: '具体的な問題（お金・手続き・仕事など）',
        biasHints: { B1: 1, B7: 1 },
        jungShadowHints: { Te: 1, Si: 1 },
        attackTypeHints: { jin_84: 1, jin_89: 1 },
        tags: ['practical'],
      },
    ],
  },

  {
    id: 'atk_sb_011',
    type: 'probe',
    text: 'そのきょうだいはあなたが困っているとき、どう反応しますか？',
    discriminates: [],
    choices: [
      {
        id: 'actively_helps',
        label: '率先して助けようとする',
        biasHints: { B4: 1, B8: 1 },
        jungShadowHints: { Fe: 3, Te: 1 },
        attackTypeHints: { jin_89: 3, jin_87: 2 },
        tags: ['helps'],
      },
      {
        id: 'sympathizes',
        label: '「大変だね」と共感はするが具体的な行動はしない',
        biasHints: { B8: 1, B4: 1 },
        jungShadowHints: { Fe: 2 },
        attackTypeHints: { jin_85: 2, jin_89: 1 },
        tags: ['sympathize'],
      },
      {
        id: 'ignores',
        label: 'あまり反応しない・自分のことで精一杯',
        biasHints: { B9: 2 },
        jungShadowHints: { Ti: 2, Te: 1 },
        attackTypeHints: { jin_84: 2, jin_88: 2 },
        tags: ['ignores'],
      },
      {
        id: 'makes_about_them',
        label: '話を聞きながらいつの間にか自分の話になる',
        biasHints: { B5: 2, B9: 1 },
        jungShadowHints: { Fe: 1, Se: 1 },
        attackTypeHints: { jin_85: 2, jin_86: 1 },
        tags: ['deflects'],
      },
    ],
  },

  {
    id: 'atk_sb_012',
    type: 'probe',
    text: 'そのきょうだいはあなたの生活に「口出し」してきますか？',
    discriminates: [],
    choices: [
      {
        id: 'yes_often',
        label: '頼まれてもいないのによく意見してくる',
        biasHints: { B5: 2, B3: 1 },
        jungShadowHints: { Te: 2, Fe: 1 },
        attackTypeHints: { jin_84: 3, jin_87: 2 },
        tags: ['intrusive'],
      },
      {
        id: 'occasionally',
        label: 'たまに言ってくることはあるが気にならない程度',
        biasHints: {},
        jungShadowHints: { Fe: 1 },
        attackTypeHints: { jin_85: 1, jin_89: 1 },
        tags: ['occasional'],
      },
      {
        id: 'rarely',
        label: 'ほとんど言ってこない',
        biasHints: {},
        jungShadowHints: { Ti: 1, Fi: 1 },
        attackTypeHints: { jin_88: 3, jin_86: 1 },
        tags: ['rarely'],
      },
      {
        id: 'only_if_asked',
        label: '聞いたときだけ答える',
        biasHints: {},
        jungShadowHints: { Fi: 1, Ti: 1 },
        attackTypeHints: { jin_89: 1, jin_88: 2 },
        tags: ['only_if_asked'],
      },
    ],
  },

];
