// 自己理解ドメイン質問
// intent: self_understand
// 状況: s_self_esteem / s_emotion_control / s_no_direction / s_burnout

export const SELF_QUESTIONS = [

  // ── 入口 ────────────────────────────────────────────────────────────
  {
    id: 's_entry_001',
    startFor: 'self_understand',
    type: 'entry',
    text: '最近、自分のことを考えるとき、どの感覚に一番近いですか？',
    discriminates: ['s_self_esteem', 's_emotion_control', 's_no_direction', 's_burnout'],
    choices: [
      {
        id: 'self_low',
        label: '自分はダメだ、足りないという感覚がずっと続いている',
        situationScores: { s_self_esteem: 2 },
        biasHints: { B3: 1 },
        jungHints: { Fi: 1 },
        tags: ['self_esteem_domain'],
      },
      {
        id: 'emotion_wild',
        label: '感情の波が激しくて、自分でも疲れる',
        situationScores: { s_emotion_control: 2 },
        biasHints: { B8: 1 },
        jungHints: { Fe: 1 },
        tags: ['emotion_domain'],
      },
      {
        id: 'no_direction',
        label: '何のためにこれをやっているのか、見えなくなっている',
        situationScores: { s_no_direction: 2 },
        biasHints: { B6: 1 },
        jungHints: { Ni: 1 },
        tags: ['direction_domain'],
      },
      {
        id: 'burnout',
        label: 'やる気がわかない。疲れてもいないのに、動けない',
        situationScores: { s_burnout: 2 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['burnout_domain'],
      },
      {
        // 2026-07-09追加：困っていない人の逃げ場（分岐ゲート）。
        // 選択時はApp.jsx側でAkinatorループに入らずトピック選択へ戻す。
        id: 'self_ok',
        label: '今日も特に何も考えず、いつも通り過ごせている',
        tags: ['topic_ok'],
      },
    ],
  },

  // ── 自己肯定感トラック ────────────────────────────────────────────────
  {
    id: 's_esteem_001',
    type: 'follow',
    text: '誰かに「よくできていたよ」と言われたとき、最初に浮かぶのはどちらですか？',
    discriminates: ['s_self_esteem', 's_no_direction'],
    choices: [
      {
        id: 'doubt',
        label: '「お世辞かな」「本当にそう思っているのかな」と疑う',
        situationScores: { s_self_esteem: 2 },
        biasHints: { B3: 1 },
        jungHints: { Ti: 1 },
        tags: ['praise_doubt'],
      },
      {
        id: 'accept',
        label: '「ありがとう」と返して、そのまま次のことに気持ちが向かう',
        situationScores: { s_self_esteem: -2 },
        tags: ['praise_accept'],
      },
      {
        id: 'indifferent',
        label: '特に何も感じない。最近は何を言われても響かない',
        situationScores: { s_burnout: 1, s_no_direction: 1 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['praise_indifferent'],
      },
    ],
  },
  {
    id: 's_esteem_002',
    type: 'follow',
    text: 'SNSで知人が成果を報告しているのを見たとき、最初に感じるのはどれですか？',
    discriminates: ['s_self_esteem', 's_no_direction'],
    choices: [
      {
        id: 'compare',
        label: '自分と比べて、落ち込む',
        situationScores: { s_self_esteem: 2 },
        biasHints: { B4: 1 },
        jungHints: { Fi: 1 },
        tags: ['social_compare'],
      },
      {
        id: 'congrats',
        label: '「良かったね」で終わって、特にそれ以上は考えない',
        situationScores: { s_self_esteem: -2 },
        tags: ['social_congrats'],
      },
      {
        id: 'detach',
        label: 'うらやましいというより、自分には関係ない話だと感じる',
        situationScores: { s_burnout: 1, s_no_direction: 1 },
        jungHints: { Ni: 1 },
        tags: ['social_detach'],
      },
    ],
  },
  {
    id: 's_esteem_003',
    type: 'follow',
    text: '何かをミスしたとき、その後どうなりますか？',
    discriminates: ['s_self_esteem', 's_emotion_control'],
    choices: [
      {
        id: 'ruminate',
        label: '何日もそのことが頭から離れず、自分を責め続ける',
        situationScores: { s_self_esteem: 2, s_emotion_control: 1 },
        biasHints: { B8: 1 },
        jungHints: { Fi: 1 },
        tags: ['mistake_ruminate'],
      },
      {
        id: 'move_on',
        label: '反省はするが、次に向けてすぐ切り替えられる',
        situationScores: { s_self_esteem: -2 },
        tags: ['mistake_moveon'],
      },
      {
        id: 'numb',
        label: '最近はミスしても、何も感じなくなってきた',
        situationScores: { s_burnout: 2 },
        biasHints: { B6: 1 },
        jungHints: { Si: 1 },
        tags: ['mistake_numb'],
      },
    ],
  },

  // ── 感情コントロールトラック ──────────────────────────────────────────
  {
    id: 's_emotion_001',
    type: 'follow',
    text: '誰かに強い言い方をされたとき、その後どうなりますか？',
    discriminates: ['s_emotion_control', 's_self_esteem'],
    choices: [
      {
        id: 'linger',
        label: '怒りや傷ついた気持ちが、何時間も消えない',
        situationScores: { s_emotion_control: 2, s_self_esteem: 1 },
        biasHints: { B8: 1 },
        jungHints: { Fe: 1 },
        tags: ['emotion_linger'],
      },
      {
        id: 'explode',
        label: '瞬間的に感情が出て、後で後悔する',
        situationScores: { s_emotion_control: 2 },
        biasHints: { B8: 1 },
        jungHints: { Se: 1 },
        tags: ['emotion_explode'],
      },
      {
        id: 'suppress',
        label: 'その場では何も言えず、後でモヤモヤが残る',
        situationScores: { s_emotion_control: 1, s_self_esteem: 1 },
        jungHints: { Fi: 1 },
        tags: ['emotion_suppress'],
      },
    ],
  },
  {
    id: 's_emotion_002',
    type: 'follow',
    text: '気分が沈んでいるとき、何がきっかけか分かりますか？',
    discriminates: ['s_emotion_control', 's_burnout'],
    choices: [
      {
        id: 'unknown',
        label: '理由が分からないまま、気づいたら落ちている',
        situationScores: { s_emotion_control: 2, s_burnout: 1 },
        biasHints: { B8: 1 },
        jungHints: { Ni: 1 },
        tags: ['emotion_unknown'],
      },
      {
        id: 'known',
        label: 'きっかけは分かるが、どうすればいいか分からない',
        situationScores: { s_emotion_control: 1, s_no_direction: 1 },
        jungHints: { Ti: 1 },
        tags: ['emotion_known'],
      },
      {
        id: 'flat',
        label: '沈んでいるというより、ずっとフラットで何も感じない',
        situationScores: { s_burnout: 2 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['emotion_flat'],
      },
    ],
  },
  {
    id: 's_emotion_003',
    type: 'follow',
    text: '人前で感情を出してしまったあと、どう感じますか？',
    discriminates: ['s_emotion_control', 's_self_esteem'],
    choices: [
      {
        id: 'regret',
        label: 'ひどく後悔して、また自分を責める',
        situationScores: { s_emotion_control: 1, s_self_esteem: 2 },
        biasHints: { B8: 1 },
        jungHints: { Fi: 1 },
        tags: ['emotion_regret'],
      },
      {
        id: 'shame',
        label: '恥ずかしくて、その場から消えたくなる',
        situationScores: { s_emotion_control: 2 },
        biasHints: { B4: 1 },
        jungHints: { Fe: 1 },
        tags: ['emotion_shame'],
      },
      {
        id: 'numb2',
        label: '最近は感情が出ること自体が減っている',
        situationScores: { s_burnout: 2, s_emotion_control: 1 },
        jungHints: { Si: 1 },
        tags: ['emotion_numb'],
      },
    ],
  },

  // ── 方向性トラック ────────────────────────────────────────────────────
  {
    id: 's_direction_001',
    type: 'follow',
    text: '5年後の自分を想像しようとすると、どうなりますか？',
    discriminates: ['s_no_direction', 's_burnout'],
    choices: [
      {
        id: 'blank',
        label: '何も浮かばない。白紙のままで、不安だけがある',
        situationScores: { s_no_direction: 2 },
        biasHints: { B6: 1 },
        jungHints: { Ni: 1 },
        tags: ['future_blank'],
      },
      {
        id: 'many',
        label: '選択肢が多すぎて、どれが自分に合っているか分からない',
        situationScores: { s_no_direction: 2 },
        biasHints: { B7: 1 },
        jungHints: { Ne: 1 },
        tags: ['future_many'],
      },
      {
        id: 'dontcare',
        label: '想像する気力がない。先のことを考えられない',
        situationScores: { s_burnout: 2, s_no_direction: 1 },
        jungHints: { Si: 1 },
        tags: ['future_dontcare'],
      },
    ],
  },
  {
    id: 's_direction_002',
    type: 'follow',
    text: '何かを決めなければならない場面で、どうなることが多いですか？',
    discriminates: ['s_no_direction', 's_self_esteem'],
    choices: [
      {
        id: 'delay',
        label: 'ギリギリまで決められず、後で後悔する',
        situationScores: { s_no_direction: 2 },
        biasHints: { B6: 1 },
        jungHints: { Fi: 1 },
        tags: ['decision_delay'],
      },
      {
        id: 'other',
        label: '誰かに決めてもらいたくなる',
        situationScores: { s_no_direction: 1, s_self_esteem: 1 },
        biasHints: { B4: 1 },
        jungHints: { Fe: 1 },
        tags: ['decision_other'],
      },
      {
        id: 'regret2',
        label: 'どちらを選んでも後悔しそうで、どちらも選べない',
        situationScores: { s_no_direction: 2, s_self_esteem: 1 },
        biasHints: { B1: 1 },
        jungHints: { Ni: 1 },
        tags: ['decision_regret'],
      },
    ],
  },
  {
    id: 's_direction_003',
    type: 'follow',
    text: '「これをやっていてよかった」と思えた瞬間は、最後にいつでしたか？',
    discriminates: ['s_no_direction', 's_burnout'],
    choices: [
      {
        id: 'long_ago',
        label: 'かなり前のことで、最近は思い出せない',
        situationScores: { s_no_direction: 1, s_burnout: 2 },
        biasHints: { B6: 1 },
        jungHints: { Si: 1 },
        tags: ['meaning_lost'],
      },
      {
        id: 'never',
        label: 'そういう感覚自体、あまり経験がない気がする',
        situationScores: { s_no_direction: 2, s_self_esteem: 1 },
        biasHints: { B3: 1 },
        jungHints: { Fi: 1 },
        tags: ['meaning_never'],
      },
      {
        id: 'fleeting',
        label: 'たまにはあるが、すぐ消える',
        situationScores: { s_no_direction: 1 },
        jungHints: { Ne: 1 },
        tags: ['meaning_fleeting'],
      },
    ],
  },

  // ── 燃え尽きトラック ──────────────────────────────────────────────────
  {
    id: 's_burnout_001',
    type: 'follow',
    text: '仕事のある朝、起きたときの最初の感覚はどれですか？',
    discriminates: ['s_burnout', 's_emotion_control'],
    choices: [
      {
        id: 'heavy',
        label: '体が重い。起き上がるまでに時間がかかる',
        situationScores: { s_burnout: 2 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['morning_heavy'],
      },
      {
        id: 'dread',
        label: '今日も行かなければという気持ちが、まず来る',
        situationScores: { s_burnout: 1, s_emotion_control: 1 },
        biasHints: { B1: 1 },
        jungHints: { Fe: 1 },
        tags: ['morning_dread'],
      },
      {
        id: 'auto',
        label: '何も感じない。自動的に動いている感じ',
        situationScores: { s_burnout: 2 },
        biasHints: { B6: 1 },
        jungHints: { Si: 1 },
        tags: ['morning_auto'],
      },
    ],
  },
  {
    id: 's_burnout_002',
    type: 'follow',
    text: '昔は好きだったことや趣味が、最近どうなっていますか？',
    discriminates: ['s_burnout', 's_no_direction'],
    choices: [
      {
        id: 'stopped',
        label: 'いつのまにかやらなくなっていて、やる気も起きない',
        situationScores: { s_burnout: 2 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['hobby_stopped'],
      },
      {
        id: 'lost',
        label: '好きなものが何なのか、よく分からなくなった',
        situationScores: { s_burnout: 1, s_no_direction: 1 },
        jungHints: { Ni: 1 },
        tags: ['hobby_lost'],
      },
      {
        id: 'insufficient',
        label: '好きなものはあるが、それだけでは満たされない',
        situationScores: { s_no_direction: 1 },
        jungHints: { Ne: 1 },
        tags: ['hobby_insufficient'],
      },
    ],
  },
  {
    id: 's_burnout_003',
    type: 'follow',
    text: '何かを終えたとき（仕事・タスク・予定）、どんな感覚がありますか？',
    discriminates: ['s_burnout', 's_self_esteem'],
    choices: [
      {
        id: 'nothing',
        label: '終わった、という事実だけで、達成感のようなものは来ない',
        situationScores: { s_burnout: 2 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['done_nothing'],
      },
      {
        id: 'relief',
        label: 'ほっとするが、喜びではなくただの解放感',
        situationScores: { s_burnout: 1, s_no_direction: 1 },
        jungHints: { Fe: 1 },
        tags: ['done_relief'],
      },
      {
        id: 'next',
        label: 'すぐ次のことが気になって、達成感を味わう間もない',
        situationScores: { s_no_direction: 1 },
        biasHints: { B2: 1 },
        jungHints: { Ne: 1 },
        tags: ['done_next'],
      },
    ],
  },

  // ── クロスカット（複数状況を横断して識別）────────────────────────────
  {
    id: 's_cross_001',
    type: 'follow',
    text: '「自分を変えたい」と思ったとき、最初に起きることはどれですか？',
    discriminates: ['s_self_esteem', 's_no_direction', 's_burnout'],
    choices: [
      {
        id: 'cant',
        label: 'どうせ変われないという気持ちが先に来る',
        situationScores: { s_self_esteem: 2 },
        biasHints: { B6: 1 },
        jungHints: { Si: 1 },
        tags: ['change_cant'],
      },
      {
        id: 'how',
        label: '変わりたいが、何をすればいいか全く分からない',
        situationScores: { s_no_direction: 2 },
        biasHints: { B6: 1 },
        jungHints: { Ni: 1 },
        tags: ['change_how'],
      },
      {
        id: 'energy',
        label: '変わりたいという気持ち自体が、最近出てこない',
        situationScores: { s_burnout: 2 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['change_energy'],
      },
    ],
  },
  {
    id: 's_cross_002',
    type: 'follow',
    text: '一人でいるとき、頭の中で何が一番繰り返されていますか？',
    discriminates: ['s_self_esteem', 's_emotion_control', 's_no_direction'],
    choices: [
      {
        id: 'past',
        label: '過去の失敗や、恥ずかしかった場面',
        situationScores: { s_self_esteem: 2, s_emotion_control: 1 },
        biasHints: { B8: 1 },
        jungHints: { Si: 1 },
        tags: ['alone_past'],
      },
      {
        id: 'future_worry',
        label: '将来への漠然とした不安',
        situationScores: { s_no_direction: 2 },
        biasHints: { B1: 1 },
        jungHints: { Ni: 1 },
        tags: ['alone_future'],
      },
      {
        id: 'empty',
        label: '何も考えていない。頭が空っぽになっている',
        situationScores: { s_burnout: 2 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        tags: ['alone_empty'],
      },
    ],
  },
  {
    id: 's_cross_003',
    type: 'follow',
    text: '「頑張らなきゃ」という気持ちと、今の自分はどちらに近いですか？',
    discriminates: ['s_self_esteem', 's_burnout', 's_no_direction'],
    choices: [
      {
        id: 'pressure',
        label: '頑張らなきゃと思うのに動けない自分が、嫌になる',
        situationScores: { s_self_esteem: 2, s_emotion_control: 1 },
        biasHints: { B8: 1 },
        jungHints: { Fi: 1 },
        tags: ['effort_pressure'],
      },
      {
        id: 'exhaust',
        label: '頑張ること自体が、もう疲れた',
        situationScores: { s_burnout: 2 },
        biasHints: { B6: 1 },
        jungHints: { Si: 1 },
        tags: ['effort_exhaust'],
      },
      {
        id: 'direction_miss',
        label: '頑張る方向が分からないから、頑張れない',
        situationScores: { s_no_direction: 2 },
        biasHints: { B6: 1 },
        jungHints: { Ni: 1 },
        tags: ['effort_direction'],
      },
    ],
  },
];
