// 汎用入口質問（全5問）
// - 全ドメイン・全年代・全職業に対応
// - 何を測っているか見えない
// - situationScores + biasHints + jungHints + demographicHints を全部持つ
// - Q5の答えは結果画面で読み返す（ゾクっポイント）

export const UNIVERSAL_QUESTIONS = [

  {
    id: 'u_001',
    type: 'universal',
    order: 1,
    text: '一日が終わるとき、どの感覚が一番近いですか？',
    discriminates: ['w_work_overload', 's_burnout', 'r_partner_drift', 's_emotion_control'],
    choices: [
      {
        id: 'drained',
        label: '消耗した。でも何に消耗したかよく分からない',
        situationScores: { w_work_overload: 2, s_burnout: 1 },
        biasHints: { B8: 1 },
        jungHints: { Si: 1 },
        demographicHints: { age_30s: 1, job_employee: 1 },
        tags: ['day_drained'],
      },
      {
        id: 'want_alone',
        label: '早く一人になって、静かにしたい',
        situationScores: { s_emotion_control: 1, w_col_isolation: 1, r_friend_isolation: 1 },
        biasHints: { B6: 1 },
        jungHints: { Fi: 1 },
        demographicHints: { age_30s: 1, age_40s: 1 },
        tags: ['day_alone'],
      },
      {
        id: 'want_talk',
        label: '誰かに今日のことを話したい',
        situationScores: { r_partner_drift: 2, r_friend_isolation: 1 },
        biasHints: { B4: 1 },
        jungHints: { Fe: 1 },
        demographicHints: { age_late20s: 1, age_30s: 1 },
        tags: ['day_talk'],
      },
      {
        id: 'day_fulfilled',
        label: '今日もやりきった。充実していた',
        situationScores: {},
        jungHints: { Te: 1 },
        tags: ['day_fulfilled'],
      },
    ],
  },

  {
    id: 'u_002',
    type: 'universal',
    order: 2,
    text: '急な出費が重なったとき、最初に頭をよぎるのはどれですか？',
    discriminates: ['w_career_change', 'f_job_decision', 's_burnout', 'r_parent_care'],
    choices: [
      {
        id: 'salary_day',
        label: '給料日まで持つか確認する',
        situationScores: { w_work_overload: 1, w_career_stuck: 1 },
        jungHints: { Si: 1 },
        demographicHints: { job_employee: 2, age_late20s: 1, age_30s: 1 },
        tags: ['money_employee'],
      },
      {
        id: 'next_invoice',
        label: '来月の入金があるかを確認する',
        situationScores: { f_independence: 1, w_career_indep: 1 },
        jungHints: { Ni: 1 },
        demographicHints: { job_freelance: 2, age_30s: 1 },
        tags: ['money_freelance'],
      },
      {
        id: 'family_budget',
        label: '家計のやりくりを考える',
        situationScores: { r_parent_care: 1, f_life_change: 1 },
        jungHints: { Si: 1 },
        demographicHints: { job_homemaker: 2, age_30s: 1, age_40s: 1 },
        tags: ['money_homemaker'],
      },
      {
        id: 'shift_more',
        label: 'シフトを増やすか、節約できるか考える',
        situationScores: { s_no_direction: 1, f_job_decision: 1 },
        jungHints: { Ne: 1 },
        demographicHints: { job_student: 2, job_parttime: 2, age_early20s: 2 },
        tags: ['money_student'],
      },
    ],
  },

  {
    id: 'u_003',
    type: 'universal',
    order: 3,
    text: '身近な人が、今の仕事や立場を突然辞めたと聞いたとき、まず思うのはどれですか？',
    discriminates: ['w_career_change', 'w_career_stuck', 'w_work_overload', 's_burnout'],
    choices: [
      {
        id: 'me_too',
        label: '自分も動いた方がいいかも、と頭をよぎる',
        situationScores: { w_career_change: 2, w_career_stuck: 1 },
        biasHints: { B4: 1 },
        jungHints: { Ni: 1 },
        demographicHints: { age_late20s: 2, age_30s: 1, job_employee: 1 },
        tags: ['quit_me_too'],
      },
      {
        id: 'brave',
        label: '思い切ったな、うらやましいと思う',
        situationScores: { w_career_change: 1, w_work_empty: 1, s_no_direction: 1 },
        biasHints: { B6: 1 },
        jungHints: { Ne: 1 },
        demographicHints: { age_30s: 2, age_40s: 1 },
        tags: ['quit_brave'],
      },
      {
        id: 'work_pile',
        label: 'その人の分の負担が来そうで、憂鬱になる',
        situationScores: { w_work_overload: 2, s_burnout: 1 },
        biasHints: { B1: 1 },
        jungHints: { Si: 1 },
        demographicHints: { job_employee: 2, age_30s: 1, age_40s: 1 },
        tags: ['quit_workpile'],
      },
      {
        id: 'own_path',
        label: 'よかったな、と思った。自分には自分のやることがある',
        situationScores: {},
        jungHints: { Te: 1 },
        tags: ['quit_own_path'],
      },
    ],
  },

  {
    id: 'u_004',
    type: 'universal',
    order: 4,
    text: '自分より少し上の世代の生活を見て、どんな感覚がありますか？',
    discriminates: ['s_no_direction', 'f_job_decision', 's_self_esteem', 's_burnout'],
    choices: [
      {
        id: 'want_that',
        label: 'あの生活に近づきたい、と思う',
        situationScores: { s_no_direction: 1, f_job_decision: 1 },
        biasHints: { B4: 1 },
        jungHints: { Ne: 1 },
        demographicHints: { age_early20s: 2, age_late20s: 1 },
        tags: ['gen_aspire'],
      },
      {
        id: 'already_there',
        label: '気づいたら自分がもうその年代だった、という実感がある',
        situationScores: { s_no_direction: 1, w_career_stuck: 1 },
        biasHints: { B6: 1 },
        jungHints: { Si: 1 },
        demographicHints: { age_30s: 2, age_40s: 1 },
        tags: ['gen_already'],
      },
      {
        id: 'stopped_comparing',
        label: '比べることを、いつからかやめていた',
        situationScores: { s_burnout: 1, s_self_esteem: 1 },
        biasHints: { B6: 1 },
        jungHints: { Fi: 1 },
        demographicHints: { age_40s: 2, age_50s: 1, age_60s: 2 },
        tags: ['gen_stopped'],
      },
      {
        id: 'different_world',
        label: '自分とは別の世界の話に見える',
        situationScores: { s_burnout: 2, r_friend_isolation: 1 },
        biasHints: { B2: 1 },
        jungHints: { Si: 1 },
        demographicHints: { age_early20s: 1, age_30s: 1 },
        tags: ['gen_different'],
      },
    ],
  },

  {
    id: 'u_005',
    type: 'universal',
    order: 5,
    // この答えは結果画面の冒頭で読み返す（最大ゾクっポイント）
    text: '今の自分の状態に、一番近い言葉はどれですか？',
    discriminates: ['s_self_esteem', 's_burnout', 's_no_direction', 'r_partner_drift', 'w_work_overload'],
    choices: [
      {
        id: 'spinning',
        label: '頑張っているのに、何かが空回りしている',
        situationScores: { s_self_esteem: 2, w_career_stuck: 1 },
        biasHints: { B8: 1 },
        jungHints: { Fi: 1 },
        tags: ['state_spinning'],
      },
      {
        id: 'tired_of_trying',
        label: '頑張ること自体が、しんどくなってきた',
        situationScores: { s_burnout: 2, w_work_overload: 1 },
        biasHints: { B6: 1 },
        jungHints: { Si: 1 },
        demographicHints: { age_30s: 1, age_40s: 1, age_50s: 1, age_60s: 1 },
        tags: ['state_tired'],
      },
      {
        id: 'lost_direction',
        label: '頑張る方向が分からなくて、動けない',
        situationScores: { s_no_direction: 2, f_job_decision: 1 },
        biasHints: { B6: 1 },
        jungHints: { Ni: 1 },
        tags: ['state_lost'],
      },
      {
        id: 'state_stable',
        label: '今は落ち着いている。ただ、この先のことが少し気になっている',
        situationScores: { s_no_direction: 1, f_job_decision: 1 },
        jungHints: { Ni: 1 },
        tags: ['state_stable'],
      },
    ],
  },
];
