# -*- coding: utf-8 -*-
"""Thumbnail generation: OpenAI raw image + Pillow text overlay.

Phase 2 of the Gachijin pipeline. Produces:
- raw_dayN.png — 1280x670 PNG with **no text**, generated by OpenAI gpt-image-1
- final_dayN.png — 1280x670 PNG with main_text/sub_text overlaid via Pillow

When ``OPENAI_API_KEY`` is missing or ``dry_run=True``, a deterministic gradient
backdrop is used instead so the rest of the pipeline can still be exercised
locally.
"""
from __future__ import annotations

import base64
import io
import logging
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib import error, request

logger = logging.getLogger(__name__)

IMAGE_SIZE = (1280, 670)
OPENAI_IMAGE_MODEL = os.environ.get("GACHIJIN_IMAGE_MODEL", "gpt-image-1")
OPENAI_IMAGE_ENDPOINT = "https://api.openai.com/v1/images/generations"

# OpenAI gpt-image-1 only accepts square or 16:9 portrait/landscape sizes
# (1024x1024, 1024x1536, 1536x1024). 1536x1024 is the closest landscape that
# we then crop down to 1280x670.
OPENAI_REQUEST_SIZE = "1536x1024"

NEGATIVE_HINTS = (
    "no text, no letters, no Japanese characters, no English characters, "
    "no symbols, no logos, no captions, no posters, no signage, "
    "no hourglass, no chains, no abstract metaphor objects"
)

STYLE_BASE = (
    "Photorealistic candid photograph of a Japanese person in their 20s to 40s, "
    "realistic everyday scene, morning to daytime natural light, soft natural shadows, "
    "clean simple composition, person on the LEFT third of the frame, "
    "large empty space on the RIGHT half for later Japanese text overlay, "
    "shallow depth of field, slightly cinematic but understated. "
)

COLOR_PRESETS = {
    "gold_black": {
        "fill": (224, 198, 138),
        "stroke": (24, 18, 10),
        "stroke_width": 2,
        "shadow": (0, 0, 0, 140),
        "shadow_offset": (1, 2),
        "shadow_blur": 6,
    },
    "white_black": {
        "fill": (250, 248, 244),
        "stroke": (15, 12, 10),
        "stroke_width": 2,
        "shadow": (0, 0, 0, 160),
        "shadow_offset": (1, 2),
        "shadow_blur": 6,
    },
    "black_white": {
        "fill": (24, 18, 12),
        "stroke": (250, 248, 244),
        "stroke_width": 2,
        "shadow": (255, 255, 255, 130),
        "shadow_offset": (1, 2),
        "shadow_blur": 6,
    },
}

# Japanese punctuation we prefer to break AFTER, never BEFORE
BREAK_AFTER = set("、。！？・…」』）]〉》〕")
NEVER_LEAD = set("、。！？・…」』）]〉》〕ぁぃぅぇぉっゃゅょゎァィゥェォッャュョヮ")
NEVER_TRAIL = set("「『（［〈《〔")

FONT_CANDIDATES = (
    # Linux (GitHub Actions ubuntu-latest after `apt install fonts-noto-cjk`)
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJKjp-Bold.otf",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Bold.ttc",
    # macOS
    "/Library/Fonts/Hiragino Sans GB W6.otf",
    "/System/Library/Fonts/HelveticaNeue.ttc",
    # Windows
    "C:\\Windows\\Fonts\\YuGothB.ttc",
    "C:\\Windows\\Fonts\\meiryob.ttc",
    "C:\\Windows\\Fonts\\msgothic.ttc",
)


@dataclass
class ThumbnailArtifacts:
    raw_path: Path
    final_path: Path
    source: str  # "openai" or "dry_run"


def _build_image_prompt(moment: str, action_type: str) -> str:
    return (
        f"{STYLE_BASE}"
        f"Action category: {action_type}. "
        f"Scene: {moment}. "
        f"{NEGATIVE_HINTS}, "
        "natural Japanese workplace or home interior, "
        "high quality candid photography aesthetic, "
        "16:9 landscape composition."
    )


def _request_openai_image(prompt: str, api_key: str) -> bytes:
    body = {
        "model": OPENAI_IMAGE_MODEL,
        "prompt": prompt,
        "size": OPENAI_REQUEST_SIZE,
        "n": 1,
    }
    import json as _json

    req = request.Request(
        OPENAI_IMAGE_ENDPOINT,
        data=_json.dumps(body).encode("utf-8"),
        method="POST",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    try:
        with request.urlopen(req, timeout=120) as res:
            payload = _json.loads(res.read().decode("utf-8"))
    except error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"OpenAI image API failed: {exc.code} {detail}") from exc

    item = payload["data"][0]
    if "b64_json" in item and item["b64_json"]:
        return base64.b64decode(item["b64_json"])
    if "url" in item and item["url"]:
        with request.urlopen(item["url"], timeout=60) as res:
            return res.read()
    raise RuntimeError("OpenAI image response did not contain b64_json or url")


def _resize_to_thumbnail(image_bytes: bytes) -> bytes:
    from PIL import Image  # type: ignore

    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    target_w, target_h = IMAGE_SIZE
    src_ratio = img.width / img.height
    tgt_ratio = target_w / target_h
    if src_ratio > tgt_ratio:
        new_w = int(img.height * tgt_ratio)
        offset = (img.width - new_w) // 2
        img = img.crop((offset, 0, offset + new_w, img.height))
    elif src_ratio < tgt_ratio:
        new_h = int(img.width / tgt_ratio)
        offset = (img.height - new_h) // 2
        img = img.crop((0, offset, img.width, offset + new_h))
    img = img.resize(IMAGE_SIZE, Image.LANCZOS)
    out = io.BytesIO()
    img.save(out, format="PNG")
    return out.getvalue()


def _generate_dry_run_image(moment: str, day_no: int) -> bytes:
    """Full-bleed photo-like placeholder. NO frame, NO labels, NO panels.

    The placeholder mimics a real candid photograph: a soft natural-light
    backdrop with a darker silhouette band on the LEFT (where a person would
    be) and an open RIGHT side (where text will be composited). Looks like a
    blurred photo, not a development screen.
    """
    from PIL import Image, ImageDraw, ImageFilter  # type: ignore

    # Tone per day so the three days feel like one visual series with subtle
    # progression (morning warm / midday neutral / late afternoon)
    tones = [
        ((232, 220, 198), (188, 162, 124)),  # warm morning
        ((216, 210, 198), (160, 150, 132)),  # neutral midday
        ((204, 192, 174), (132, 116, 96)),   # late afternoon
    ]
    top_rgb, bottom_rgb = tones[(day_no - 1) % len(tones)]

    img = Image.new("RGB", IMAGE_SIZE, top_rgb)
    draw = ImageDraw.Draw(img)
    # Vertical gradient (ceiling lighter, floor darker — natural interior light)
    for y in range(IMAGE_SIZE[1]):
        t = y / IMAGE_SIZE[1]
        r = int(top_rgb[0] + (bottom_rgb[0] - top_rgb[0]) * t)
        g = int(top_rgb[1] + (bottom_rgb[1] - top_rgb[1]) * t)
        b = int(top_rgb[2] + (bottom_rgb[2] - top_rgb[2]) * t)
        draw.line(((0, y), (IMAGE_SIZE[0], y)), fill=(r, g, b))

    # Soft "person" silhouette on left third — large blurred ellipse, not a
    # box. Reads as out-of-focus subject, never as a UI element.
    silhouette = Image.new("RGBA", IMAGE_SIZE, (0, 0, 0, 0))
    sil_draw = ImageDraw.Draw(silhouette)
    body_color = (
        max(top_rgb[0] - 70, 30),
        max(top_rgb[1] - 70, 26),
        max(top_rgb[2] - 60, 22),
        140,
    )
    # head
    sil_draw.ellipse((180, 110, 360, 290), fill=body_color)
    # torso
    sil_draw.ellipse((100, 260, 460, 720), fill=body_color)
    silhouette = silhouette.filter(ImageFilter.GaussianBlur(radius=28))
    img = Image.alpha_composite(img.convert("RGBA"), silhouette).convert("RGB")

    # Subtle light vignette from upper-left (window light)
    vignette = Image.new("RGBA", IMAGE_SIZE, (0, 0, 0, 0))
    v_draw = ImageDraw.Draw(vignette)
    v_draw.ellipse((-200, -240, 700, 480), fill=(255, 244, 220, 70))
    vignette = vignette.filter(ImageFilter.GaussianBlur(radius=80))
    img = Image.alpha_composite(img.convert("RGBA"), vignette).convert("RGB")

    # Final atmospheric blur so it never reads as flat graphic
    img = img.filter(ImageFilter.GaussianBlur(radius=1.4))

    out = io.BytesIO()
    img.save(out, format="PNG")
    return out.getvalue()


def _load_font(size: int):
    from PIL import ImageFont  # type: ignore

    for path in FONT_CANDIDATES:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size=size)
            except OSError:
                continue
    return ImageFont.load_default()


def _measure(draw, text: str, font) -> tuple[int, int]:
    try:
        bbox = draw.textbbox((0, 0), text, font=font, stroke_width=0)
        return bbox[2] - bbox[0], bbox[3] - bbox[1]
    except AttributeError:
        return font.getsize(text)


def _wrap_to_width(text: str, font, draw, max_width: int) -> list[str]:
    """Width-aware wrap that respects Japanese kinsoku (no leading 。、 etc.)."""
    if not text:
        return []
    if _measure(draw, text, font)[0] <= max_width:
        return [text]
    lines: list[str] = []
    current = ""
    for i, ch in enumerate(text):
        prev = current[-1] if current else ""
        candidate = current + ch
        fits = _measure(draw, candidate, font)[0] <= max_width
        # Hard break is OK only when both sides allow it (kinsoku)
        if not fits and current and ch not in NEVER_LEAD and prev not in NEVER_TRAIL:
            lines.append(current)
            current = ch
        else:
            current = candidate
        # Prefer to break right AFTER punctuation if next char would still overflow
        if (
            ch in BREAK_AFTER
            and i + 1 < len(text)
            and _measure(draw, current + text[i + 1], font)[0] > max_width
        ):
            lines.append(current)
            current = ""
    if current:
        lines.append(current)
    return lines


def _is_hiragana(ch: str) -> bool:
    return "぀" <= ch <= "ゟ"


def _is_kanji(ch: str) -> bool:
    return "一" <= ch <= "鿿"


def _is_katakana(ch: str) -> bool:
    return "゠" <= ch <= "ヿ"


# Common single-char particles that reliably end a clause
PARTICLE_AFTER = set("はがをにでとへも")
# Hiragana that typically begin a new word/clause
CLAUSE_LEAD = set("そあこ")


def _break_score(text: str, idx: int) -> int:
    """Lower is better. Penalises breaks that split semantic units."""
    prev, nxt = text[idx - 1], text[idx]
    score = 0
    # Prefer break AFTER punctuation
    if prev in BREAK_AFTER:
        score -= 50
    # Reward break after a clause particle (が、を、に...)
    if prev in PARTICLE_AFTER:
        score -= 12
    # Reward break before a clause-leading hiragana
    if nxt in CLAUSE_LEAD:
        score -= 6
    # Penalise breaking between two hiragana (likely inside a word/inflection)
    if _is_hiragana(prev) and _is_hiragana(nxt):
        score += 30
    # Penalise breaking between two kanji (likely inside a compound)
    if _is_kanji(prev) and _is_kanji(nxt):
        score += 20
    # Penalise breaking between two katakana (foreign word)
    if _is_katakana(prev) and _is_katakana(nxt):
        score += 25
    # Reward break after hiragana run (often particle ends)
    if _is_hiragana(prev) and (_is_kanji(nxt) or _is_katakana(nxt)):
        score -= 8
    # Reward break before hiragana (often start of new clause)
    if (_is_kanji(prev) or _is_katakana(prev)) and _is_hiragana(nxt):
        score -= 5
    return score


def _balanced_wrap(text: str, font, draw, max_width: int) -> list[str]:
    """Balance a multi-line wrap with linguistic scoring.

    Only kicks in when:
      - the single-line form does NOT fit, OR
      - text is long enough (>=10 chars) that a 2-line poster look reads better.
    Both halves must have at least 3 chars; pick the highest-scoring break point.
    """
    if not text:
        return []
    full_w = _measure(draw, text, font)[0]
    fits_single = full_w <= max_width
    if fits_single and len(text) < 10:
        return [text]
    min_segment = 3
    if len(text) < min_segment * 2:
        return [text] if fits_single else _wrap_to_width(text, font, draw, max_width)
    mid = len(text) / 2
    best: tuple[int, int] | None = None  # (score, idx)
    for idx in range(min_segment, len(text) - min_segment + 1):
        if text[idx] in NEVER_LEAD or text[idx - 1] in NEVER_TRAIL:
            continue
        left, right = text[:idx], text[idx:]
        if _measure(draw, left, font)[0] > max_width or _measure(draw, right, font)[0] > max_width:
            continue
        # Linguistic score dominates; balance is a tie-breaker only
        balance = int(abs(idx - mid) * 2)
        score = _break_score(text, idx) + balance
        if best is None or score < best[0]:
            best = (score, idx)
    if best is not None:
        idx = best[1]
        return [text[:idx], text[idx:]]
    return [text] if fits_single else _wrap_to_width(text, font, draw, max_width)


def _has_orphan(lines: list[str]) -> bool:
    """An orphan is a non-final line — or a final line — with fewer than 3 chars
    while there are siblings. A single-line wrap is fine."""
    if len(lines) <= 1:
        return False
    return any(len(line) < 3 for line in lines)


def _fit_font_size(text: str, draw, max_width: int, max_height: int, start_size: int, min_size: int = 28, allow_balanced: bool = False):
    """Search for the largest font that fits text in the box without orphan lines."""
    if not text:
        return _load_font(start_size), []
    def score_lines(lines: list[str]) -> int:
        if len(lines) <= 1:
            return -100
        # Score = sum of break-point scores for inter-line breaks. Lower = better.
        # Reconstruct break indices from cumulative lengths.
        idx = 0
        total = 0
        for line in lines[:-1]:
            idx += len(line)
            total += _break_score(text, idx)
        if _has_orphan(lines):
            total += 80
        return total

    size = start_size
    fallback = None  # remember last layout that fits dimensionally even if orphaned
    while size >= min_size:
        font = _load_font(size)
        greedy = _wrap_to_width(text, font, draw, max_width)
        chosen = greedy
        if allow_balanced and len(greedy) >= 2:
            balanced = _balanced_wrap(text, font, draw, max_width)
            if len(balanced) >= 2 and score_lines(balanced) < score_lines(greedy):
                chosen = balanced
        line_h = _measure(draw, "あ", font)[1] + max(6, size // 12)
        total_h = line_h * len(chosen)
        widths_ok = all(_measure(draw, l, font)[0] <= max_width for l in chosen)
        if total_h <= max_height and widths_ok:
            if not _has_orphan(chosen):
                return font, chosen
            if fallback is None:
                fallback = (font, chosen)
        size -= 4
    if fallback is not None:
        return fallback
    font = _load_font(min_size)
    return font, _wrap_to_width(text, font, draw, max_width)


def _right_half_luminance(img) -> float:
    """Average luminance of the right text-area to decide overlay strength."""
    crop = img.crop((600, 80, IMAGE_SIZE[0] - 40, IMAGE_SIZE[1] - 80)).convert("L").resize((40, 22))
    pixels = list(crop.getdata())
    return sum(pixels) / len(pixels) / 255.0  # 0.0 dark .. 1.0 bright


def _draw_text_with_shadow(base_img, position, text, font, fill, stroke, stroke_width, shadow_rgba, shadow_offset, shadow_blur):
    """Draw text with a *soft natural* shadow plus a thin (2-4px) stroke.

    Designed to read as photographic typography, not bordered cartoon text.
    base_img must be RGBA. Returns the modified RGBA image.
    """
    from PIL import Image, ImageDraw, ImageFilter  # type: ignore

    # 1. soft shadow — small offset, gentle blur, no stroke widening
    shadow_layer = Image.new("RGBA", base_img.size, (0, 0, 0, 0))
    shadow_draw = ImageDraw.Draw(shadow_layer)
    shadow_draw.text(
        (position[0] + shadow_offset[0], position[1] + shadow_offset[1]),
        text,
        font=font,
        fill=shadow_rgba,
    )
    shadow_layer = shadow_layer.filter(ImageFilter.GaussianBlur(radius=shadow_blur))
    base_img = Image.alpha_composite(base_img, shadow_layer)

    # 2. crisp text on top with a hairline stroke for legibility on busy photos
    text_layer = Image.new("RGBA", base_img.size, (0, 0, 0, 0))
    text_draw = ImageDraw.Draw(text_layer)
    text_draw.text(
        position,
        text,
        font=font,
        fill=fill,
        stroke_width=stroke_width,
        stroke_fill=stroke,
    )
    return Image.alpha_composite(base_img, text_layer)


def _build_right_gradient_mask(luminance: float, dark_text: bool) -> "object":
    """Right-edge soft gradient that gently darkens (or lightens) the text
    area. NEVER a sharp rectangle — gradient fades from full strength on the
    right edge to fully transparent before the photo's left third.

    Strength scales with right-half luminance so dark photos get only a touch.
    """
    from PIL import Image  # type: ignore

    width, height = IMAGE_SIZE
    mask = Image.new("RGBA", IMAGE_SIZE, (0, 0, 0, 0))
    pixels = mask.load()
    # Strength: brighter photo → stronger overlay (max ~95). Dark photo → ~25.
    if dark_text:
        max_alpha = int(60 + 70 * (1.0 - luminance))  # white wash on dark photo
        rgb = (255, 250, 244)
    else:
        max_alpha = int(20 + 75 * luminance)  # black wash on bright photo
        rgb = (10, 8, 6)
    grad_start = int(width * 0.42)  # gradient begins past midline
    grad_end = width
    span = grad_end - grad_start
    for x in range(grad_start, width):
        t = (x - grad_start) / max(span, 1)
        # ease-in-out for a more natural falloff
        eased = t * t * (3 - 2 * t)
        alpha = int(eased * max_alpha)
        for y in range(height):
            pixels[x, y] = (*rgb, alpha)
    return mask


def _composite_text(raw_bytes: bytes, main_text: str, sub_text: str, color_preset: str) -> bytes:
    """Compose final thumbnail: full-bleed photo with naturally placed text.

    Strict rules (per ガチ人_ClaudeCode_サムネ修正指示.md):
      - 1280x670 entire surface IS the photo (no beige mat, no card)
      - text overlay on the right uses ONLY a soft gradient (no rectangle)
      - hairline stroke (2-4px), gentle shadow (no thick black halo)
      - main_text up to 2 lines on the right
      - sub_text below it, smaller
      - "ガチ人" label small and discreet, top-left
      - NO development labels, NO moment description text
    """
    from PIL import Image, ImageDraw  # type: ignore

    preset = COLOR_PRESETS.get(color_preset) or COLOR_PRESETS["gold_black"]
    img = Image.open(io.BytesIO(raw_bytes)).convert("RGB")
    if img.size != IMAGE_SIZE:
        img = img.resize(IMAGE_SIZE, Image.LANCZOS)

    text_x_left = 624
    text_x_right = IMAGE_SIZE[0] - 64
    max_width = text_x_right - text_x_left

    # Soft right-side gradient (NEVER a rectangle)
    luminance = _right_half_luminance(img)
    dark_text = (color_preset == "black_white")
    gradient = _build_right_gradient_mask(luminance, dark_text=dark_text)
    canvas = Image.alpha_composite(img.convert("RGBA"), gradient)
    measure_draw = ImageDraw.Draw(canvas)

    # Main text: max 2 lines, large but not crushing the photo
    main_font, main_lines = _fit_font_size(
        main_text, measure_draw, max_width, 240, 104, 56, allow_balanced=True
    )
    if len(main_lines) > 2:
        main_lines = main_lines[:2]
    sub_font, sub_lines = _fit_font_size(sub_text, measure_draw, max_width, 64, 38, 24)
    if len(sub_lines) > 1:
        sub_lines = [sub_text[: max(1, len(sub_text))]]
        sub_font, sub_lines = _fit_font_size(
            sub_text, measure_draw, max_width, 64, 36, 22
        )
        if len(sub_lines) > 1:
            sub_lines = sub_lines[:1]
    label_font = _load_font(22)

    fill = preset["fill"]
    stroke = preset["stroke"]
    stroke_width = preset["stroke_width"]
    shadow = preset["shadow"]
    shadow_offset = preset["shadow_offset"]
    shadow_blur = preset["shadow_blur"]

    line_h_main = _measure(measure_draw, "あ", main_font)[1] + 14
    line_h_sub = _measure(measure_draw, "あ", sub_font)[1] + 8
    main_block_h = line_h_main * len(main_lines)
    sub_block_h = line_h_sub * len(sub_lines)
    gap = 22
    total_h = main_block_h + gap + sub_block_h
    start_y = (IMAGE_SIZE[1] - total_h) // 2 - 8

    y = start_y
    for line in main_lines:
        canvas = _draw_text_with_shadow(
            canvas,
            (text_x_left, y),
            line,
            main_font,
            fill,
            stroke,
            stroke_width,
            shadow,
            shadow_offset,
            shadow_blur,
        )
        y += line_h_main

    y += gap
    for line in sub_lines:
        canvas = _draw_text_with_shadow(
            canvas,
            (text_x_left, y),
            line,
            sub_font,
            fill,
            stroke,
            max(stroke_width - 1, 1),
            shadow,
            shadow_offset,
            max(shadow_blur - 2, 3),
        )
        y += line_h_sub

    # ガチ人 label: top-left, small, discreet. Same color family as main text
    # but visually quiet — light shadow only, no stroke.
    label_layer = Image.new("RGBA", IMAGE_SIZE, (0, 0, 0, 0))
    label_draw = ImageDraw.Draw(label_layer)
    label_draw.text(
        (49, 41),
        "ガチ人",
        font=label_font,
        fill=(0, 0, 0, 110),
    )
    canvas = Image.alpha_composite(canvas, label_layer.filter(__import__("PIL.ImageFilter", fromlist=["GaussianBlur"]).GaussianBlur(radius=4)))
    label_layer = Image.new("RGBA", IMAGE_SIZE, (0, 0, 0, 0))
    label_draw = ImageDraw.Draw(label_layer)
    label_draw.text((48, 40), "ガチ人", font=label_font, fill=(*fill, 230))
    canvas = Image.alpha_composite(canvas, label_layer)

    out = io.BytesIO()
    canvas.convert("RGB").save(out, format="PNG")
    return out.getvalue()


def _validate_final(image_bytes: bytes) -> None:
    """Fail-fast checks against shipping a dev-screen-looking thumbnail.

    Raises ValueError with a code orchestrator can map to ``failed_composite``.
    """
    from PIL import Image  # type: ignore

    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    if img.size != IMAGE_SIZE:
        raise ValueError(f"final image size {img.size} != {IMAGE_SIZE}")

    # 1. The full canvas must look like a photo, not a flat card. Sample the
    #    standard-deviation of luminance across the whole frame; a flat beige
    #    mat will be near-zero variance.
    gray = img.convert("L").resize((64, 32))
    pixels = list(gray.getdata())
    mean = sum(pixels) / len(pixels)
    variance = sum((p - mean) ** 2 for p in pixels) / len(pixels)
    if variance < 50:
        raise ValueError(
            f"final image variance too low ({variance:.1f}) — looks like a flat card, not a photo"
        )

    # 2. No hard rectangular UI panels: detect long uniform horizontal/vertical
    #    edges in the central area which would indicate a card boundary.
    inner = img.crop((40, 40, IMAGE_SIZE[0] - 40, IMAGE_SIZE[1] - 40)).convert("L").resize((128, 64))
    px = inner.load()
    suspect_runs = 0
    for y in range(64):
        run = 0
        for x in range(1, 128):
            if abs(px[x, y] - px[x - 1, y]) <= 1:
                run += 1
                if run >= 80:
                    suspect_runs += 1
                    break
            else:
                run = 0
    if suspect_runs > 12:
        raise ValueError(
            "final image has long uniform horizontal bands — looks like a UI card, not a photo"
        )


def render_thumbnail(
    *,
    moment: str,
    main_text: str,
    sub_text: str,
    action_type: str,
    color_preset: str,
    raw_path: Path,
    final_path: Path,
    dry_run: bool,
    day_no: int,
) -> ThumbnailArtifacts:
    raw_path.parent.mkdir(parents=True, exist_ok=True)
    final_path.parent.mkdir(parents=True, exist_ok=True)

    api_key = os.environ.get("OPENAI_API_KEY")
    source = "dry_run"
    raw_bytes: bytes
    if dry_run or not api_key:
        if not api_key and not dry_run:
            logger.warning("OPENAI_API_KEY not set; falling back to dry-run gradient image")
        raw_bytes = _generate_dry_run_image(moment, day_no)
    else:
        prompt = _build_image_prompt(moment, action_type)
        try:
            generated = _request_openai_image(prompt, api_key)
            raw_bytes = _resize_to_thumbnail(generated)
            source = "openai"
        except Exception:
            logger.exception("OpenAI image generation failed; falling back to dry-run image")
            raw_bytes = _generate_dry_run_image(moment, day_no)
            source = "dry_run_fallback"

    raw_path.write_bytes(raw_bytes)
    final_bytes = _composite_text(raw_bytes, main_text, sub_text, color_preset)
    _validate_final(final_bytes)
    final_path.write_bytes(final_bytes)
    return ThumbnailArtifacts(raw_path=raw_path, final_path=final_path, source=source)
